/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2013-03-17 18:50:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.sql.*;
import java.util.*;
import java.text.*;
import java.sql.*;
import org.apache.jasper.tagplugins.jstl.core.Catch;

public final class cad_005fsenha_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/sessao1.jsp", Long.valueOf(1362944913578L));
    _jspx_dependants.put("/config.jsp", Long.valueOf(1362954014485L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("\r\n");
      out.write("//document.onkeydown = keyCatcher;\r\n");
      out.write("\r\n");
      out.write("function keyCatcher() \r\n");
      out.write("{\r\n");
      out.write("   var e = event.srcElement.tagName;\r\n");
      out.write("\r\n");
      out.write("   if (event.keyCode == 8 && e != \"INPUT\" && e != \"TEXTAREA\") \r\n");
      out.write("   {\r\n");
      out.write("      event.cancelBubble = true;\r\n");
      out.write("      event.returnValue = false;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   if (event.keyCode == 27) \r\n");
      out.write("   {\r\n");
      out.write("\t\twindow.location=\"\";\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("window.focus();\r\n");
      out.write("document.form1.nome_log.focus();\r\n");
      out.write("\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".normal {\r\n");
      out.write("\t\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("}\r\n");
      out.write(".anormal {\r\n");
      out.write("\t\tbackground-color: Lavender;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

// Titulo do Sistema
String w_titulo   = "Sistema JSP";
String w_versaox  = "Atualizado em 10/03/2013 às 17:12";

// Variaveis Banco de Dados
String driver_pes     = "com.mysql.jdbc.Driver";
String db_dados_pes   = "agenda";
String connection_pes = "jdbc:mysql://localhost:3306/" + db_dados_pes;
String user_pes       = "root";
String password_pes   = "12345";



      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Sistema XP</title>\r\n");
      out.write("<link rel='shortcut icon' href='imagens/favicon.ico'>\r\n");
      out.write("\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"menu.css\"/>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\r\n");
      out.write("background-image: url('imagens/logosys.jpg');\r\n");
      out.write("background-attachment: fixed\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".normal {\r\n");
      out.write("\t\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("}\r\n");
      out.write(".anormal {\r\n");
      out.write("\t\tbackground-color: Lavender;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\"><!--\r\n");
      out.write("\r\n");
      out.write("document.onkeydown = keyCatcher;\r\n");
      out.write("\r\n");
      out.write("function keyCatcher() \r\n");
      out.write("{\r\n");
      out.write("   var e = event.srcElement.tagName;\r\n");
      out.write("\r\n");
      out.write("   if (event.keyCode == 8 && e != \"INPUT\" && e != \"TEXTAREA\") \r\n");
      out.write("   {\r\n");
      out.write("      event.cancelBubble = true;\r\n");
      out.write("      event.returnValue = false;\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");

// Rotinas Principais

// config.jsp
// login.jsp
// logar.jsp
// menu1.jsp


      out.write("\r\n");
      out.write("\r\n");


//Declaracao de Variaveis Usadas no JSP
String situa_1 = "";
String vr1 = request.getParameter("opcao");
String ww_mensage = "";
int id_s            = 0;
String w_tabela   = "TT_SER_01"; // Tabela Banco
String w_programa = "CAD_SENHA"; // Tela
String w_nome3 = "";
String w_opcao = "";
String sol_1   = "";
String sql1    = "";
String sql2    = "";
String sql3    = "";
String sql4    = "";
String sql5    = "";

String tabelap = "";
String per1    = "";
String per2    = "";
String per3    = "";
String per4    = "";

String campo1x  = "";
String campo2x  = "";
String campo3x  = "";
String campo4x  = "";
String campo5x  = "";
String campo6x  = "";
String campo7x  = "";
String campo8x  = "";
String campo9x  = "";
String campo10x = "";
String campo11x = "";
String campo12x = "";
String campo13x = "";
String campo14x = "";
String campo15x = "";
int usuarios2 = 0;

String Cod_2 = request.getParameter("Cod_2");

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');


//Resgata informacao gravada na sessao
String Minha_sessao1 = (String) session.getAttribute("minha_sessao1");
if (Minha_sessao1 != "" || Minha_sessao1 != null){
	w_nome3 = Minha_sessao1;
	
}else{
	
	if (Minha_sessao1 == null)
	{	
	   w_opcao = "faz";
	  {response.sendRedirect("login.jsp");}
	  return;
	}  
}
if (w_nome3 == "" || w_nome3 == null){
	   w_opcao = "faz";
	  {response.sendRedirect("login.jsp");}
	  return;
}
if (w_opcao != null || w_opcao != ""){
	w_opcao = "";
	

	//Saldação ao usuario
	
	int w_Hora = Integer.parseInt((new java.text.SimpleDateFormat("HH")).format(new java.util.Date()));
	
	String w_AMPM = new java.text.SimpleDateFormat("a").format(new java.util.Date());
	
	if (w_Hora <= 0) {
	    situa_1 = "Boa Madrugada";
	    sol_1   = "imagens/noite.png";
	}
	if (w_Hora > 0 && w_Hora <= 6) {
	    situa_1 = "Boa Madrugada";
	    sol_1   = "imagens/noite.png";
	}
	if (w_Hora > 6 && w_Hora <= 12) {
	    situa_1 = "Bom Dia";
	    sol_1   = "imagens/dia.png";
	}
	if (w_Hora > 12 && w_Hora <= 18) {
	    situa_1 = "Boa Tarde";
	    sol_1   = "imagens/dia.png";
	}
	if (w_Hora >= 19 && w_Hora <= 23) {
	    situa_1 = "Boa Noite";
	    sol_1   = "imagens/noite.png";
	}
	
	
	String w_bomdia = situa_1 + " Seja Bem Vindo, " + w_nome3 + " hoje e, " + new java.text.SimpleDateFormat("EEEE dd 'de' MMMM 'de' yyyy").format(new java.util.Date()) + "<br />";
	
	String w_login        = request.getParameter("login");

	
	//Variaveis de Sessao
	
	String campo1a  = "";
	String campo2a  = "";
	String campo3a  = "";
	String campo4a  = "";
	String campo5a  = "";
	String campo6a  = "";

	// Prepara a Conexao com o Banco
	Class.forName(driver_pes);
	Connection Con = DriverManager.getConnection(connection_pes, user_pes, password_pes);
	Statement stm = Con.createStatement();

	// Busca Usuario
	sql1 = "SELECT * FROM tt_ser_01 WHERE login = '" + w_nome3 + "'";
	ResultSet res1 = stm.executeQuery(sql1);
	while(res1.next()){
		campo1a  = res1.getString("id");
		campo2a  = res1.getString("codigo");
		campo3a  = res1.getString("login");
		campo4a  = "SISTEMAXP,"+res1.getString("programas");
		campo5a  = res1.getString("tipo");
		campo6a  = res1.getString("semana");
	}
    // Fim Busca Usuario

	
	// Fim Verificar dia da Semana e Permissao da Tela 
    
	//out.println(campo1a + "<br>");
	//out.println(campo2a + "<br>");
	//out.println(campo3a + "<br>");
	//out.println(campo4a + "<br>");
	//out.println(campo5a + "<br>");
	//out.println(campo6a + "<br><br>");

	// Busca Permissao
	sql2 = "SELECT * FROM permissoes WHERE login = '" + campo3a + "' AND tabela = '" + w_tabela + "'";
	ResultSet res2 = stm.executeQuery(sql2);
	while(res2.next()){
		tabelap = res2.getString("tabela");
		per1    = res2.getString("incluir");
		per2    = res2.getString("alterar");
		per3    = res2.getString("excluir");
		per4    = res2.getString("imprimir");
	}
	// Fim Busca Permissao

	//out.println(tabelap + "<br>");
	//out.println(per1 + "<br>");
	//out.println(per2 + "<br>");
	//out.println(per3 + "<br>");
	//out.println(per4 + "<br>");

	

      out.write("\r\n");
      out.write("\r\n");
	

// Rotina Verifica Permissao da Tela 

String p_PROGM = w_programa;
String strT = campo4a;
String[] f = strT.split(",");
int fazP = 0;

for (int i= 0; i<=f.length-1; i++){	
		if (p_PROGM.toUpperCase().equals(f[i])){
			fazP = 3;
		}
}

if (fazP != 3){
	
	{response.sendRedirect("enaaurlnp.jsp");}
	
}


//Limpar Campos do Formulario
if (request.getParameter("limpar") != null) { 

	ww_mensage = "Limpar Campos";
	campo1x  = "";
	campo2x  = "";
	campo3x  = "";
	campo4x  = new java.text.SimpleDateFormat("dd/MM/yyyy").format(new java.util.Date());
	campo5x  = "";
	campo6x  = "";
	campo7x  = "";
	campo8x  = "";
	campo9x  = "";
	campo10x = "";
	campo11x = "";
	campo12x = "";
	campo13x = "";
	campo14x = "";
	campo15x = "";
    Cod_2    = "";
	
}

// Verifica se Existe Entrada
if (Cod_2 != "" || Cod_2 == null){

	sql3 = "SELECT * FROM tt_ser_01 WHERE login = '" + Cod_2 + "' ORDER BY id DESC";
	
}else{	

    sql3 = "SELECT * FROM tt_ser_01 WHERE login = '' ORDER BY id DESC";

}
// Processos dos Botoes
//Listar Registros
if (vr1 != null && vr1.equals("lis_grid")) { 

	ww_mensage = "Listar na Tela";
	//out.println(request.getParameter("opcao")  + "<br>");
	//out.println("entrei   " + request.getParameter("Cod_2") + "<br>");

}

//Listar Excluir
if (vr1 != null && vr1.equals("excluir")) { 

	ww_mensage = "<font color='red'>Excluir</font>";
	//out.println(request.getParameter("opcao")  + "<br>");
	//out.println("entrei   " + request.getParameter("Cod_2") + "<br>");

}

if (request.getParameter("resetarsenha") != null){
	
	
	if (request.getParameter("campo3") != ""){

		try  
		   {

	         ww_mensage = "Senha Redefinida";

		    // Preparação para Inclusão
		    
		    //int campo_up  = Integer.parseInt( request.getParameter("campo") );
		    String campo_up   = request.getParameter("campo");
		    String campo2_up  = request.getParameter("campo2");
		
		    // Preparação para Inclusão  
		    PreparedStatement stm1x = Con.prepareStatement("update tt_ser_01 set senha = md5(?) where id = '" + campo_up + "'");
		    
	
		    // Instancia Variavei para Salvar
		    stm1x.setString(1, campo2_up);   
		    
			stm1x.executeUpdate();   
			
		    // Sucesso 
		    stm1x.close();   
		    ww_mensage = "<font color='#0000FF'>Senha Redeficinada com Sucesso !!!</font>";
	
	        }   
	        catch(Exception ex)   
	        {   
		          // Caso ocorra Erro 
		          ww_mensage = "<font color='red'>Erro ao Redefinir Senha !!!</font>";
	
	        }  

	
}
}
	

//Listar Alterar
if (request.getParameter("alterar") != null){ 


	try  
	   {
   		    ww_mensage = "Alterar";
		    
		    // Preparação para Inclusão
		    
		    //int campo_up  = Integer.parseInt( request.getParameter("campo") );
		    String campo_up   = request.getParameter("campo");
		    String campo1_up  = request.getParameter("campo1");
		    String campo2_up  = request.getParameter("campo2");
		    String campo3_up  = request.getParameter("campo3");
		    String campo4_up  = request.getParameter("campo4");
		    String campo5_up  = request.getParameter("campo5");
		    int campo6_up = Integer.parseInt( request.getParameter( "campo6" ) );
		    //String campo6_up  = request.getParameter("campo6");
		    String campo7_up  = request.getParameter("campo7");
		    String campo8_up  = request.getParameter("campo8");
		    String campo9_up  = request.getParameter("campo9");
		    String campo10_up  = request.getParameter("campo10");
		    String campo11_up  = request.getParameter("campo11");
		    String campo12_up  = request.getParameter("campo12");
		    String campo13_up  = request.getParameter("campo13");
		    String campo14_up  = request.getParameter("campo14");
		    String campo15_up  = request.getParameter("campo15");
		
		    // Preparação para Inclusão  
		    PreparedStatement stm1 = Con.prepareStatement("update tt_ser_01 set login = ?, senha2 = md5(?), data = ?, nome = ?, maquina = ?, permissao = ?, permis2 = ?, conta = ?, programas = ?, hora1 = ?, hora2 = ?, semana = ?, e_mail = ?, tipo  = ?  where id = '" + campo_up + "'");
		    
	
		    // Instancia Variavei para Salvar
		    stm1.setString(1, campo1_up.toUpperCase());   
		    stm1.setString(2, campo2_up);   
		    stm1.setString(3, campo3_up);   
		    stm1.setString(4, campo4_up);   
		    stm1.setString(5, campo5_up);   
		    stm1.setInt(6, campo6_up);   
		    stm1.setString(7, campo7_up);   
		    stm1.setString(8, campo8_up);   
		    stm1.setString(9, campo9_up);   
		    stm1.setString(10, campo10_up);   
		    stm1.setString(11, campo11_up);   
		    stm1.setString(12, campo12_up);   
		    stm1.setString(13, campo13_up);
		    stm1.setString(14, campo14_up);
		    
			stm1.executeUpdate();   
			
		    // Sucesso 
		    stm1.close();   
		    ww_mensage = "<font color='#0000FF'>Alterado com Sucesso !!!</font>";

	   }   
	   catch(Exception ex)   
	   {   
		  // Caso ocorra Erro 
		   ww_mensage = "<font color='red'>Erro ao Alterar !!!</font>";

	   }  

	

}

//Listar Incluir
if (request.getParameter("incluir") != null) { 
	
	
	try  
	   {
			ww_mensage = "Incluir";
		    
		    // Preparação para Inclusão  
		    String campo1_sal  = request.getParameter("campo1");
		    String campo2_sal  = request.getParameter("campo2");
		    String campo3_sal  = request.getParameter("campo3");
		    String campo4_sal  = request.getParameter("campo4");
		    String campo5_sal  = request.getParameter("campo5");
		    String campo6_sal  = request.getParameter("campo6");
		    String campo7_sal  = request.getParameter("campo7");
		    String campo8_sal  = request.getParameter("campo8");
		    String campo9_sal  = request.getParameter("campo9");
		    String campo10_sal  = request.getParameter("campo10");
		    String campo11_sal  = request.getParameter("campo11");
		    String campo12_sal  = request.getParameter("campo12");
		    String campo13_sal  = request.getParameter("campo13");
		    String campo14_sal  = request.getParameter("campo14");
		    String campo15_sal  = request.getParameter("campo15");
		
		    String sql3x = "";
		    String sql3c = "";
		
			sql3x = "SELECT * FROM tt_ser_01 ORDER BY codigo ASC";	
		
		    ResultSet res3 = stm.executeQuery(sql3x);
		
		    int nu_1 = 0;
		    int mai_nu = 0;
		    
			while(res3.next()){
				
				nu_1 = res3.getInt("codigo");
			}
			mai_nu = nu_1+1;
		
		    // Preparação para Inclusão  
		    PreparedStatement stm1 = Con.prepareStatement("insert into tt_ser_01 (codigo,login,senha,data,nome,maquina,permissao,permis2,conta,programas,hora1,hora2,semana,e_mail,tipo) value (?,?,md5(?),?,?,?,?,?,?,?,?,?,?,?,?)");   
		
		    // Instancia Variavei para Salvar
		    stm1.setInt(1, mai_nu);   
		    stm1.setString(2, campo1_sal);   
		    stm1.setString(3, campo2_sal.toUpperCase());   
		    stm1.setString(4, campo3_sal);   
		    stm1.setString(5, campo4_sal);   
		    stm1.setString(6, campo5_sal);   
		    stm1.setString(7, campo6_sal);   
		    stm1.setString(8, campo7_sal);   
		    stm1.setString(9, campo8_sal);   
		    stm1.setString(10, campo9_sal);   
		    stm1.setString(11, campo10_sal);   
		    stm1.setString(12, campo11_sal);   
		    stm1.setString(13, campo12_sal);   
		    stm1.setString(14, campo13_sal);   
		    stm1.setString(15, campo14_sal);
		 	   
			stm1.executeUpdate();   
			
		    // Sucesso 
		    stm1.close();   
		    ww_mensage = "<font color='#0000FF'>Salvo com Sucesso !!!</font>";

	   }   
	   catch(Exception ex)   
	   {   
		  // Caso ocorra Erro 
		   ww_mensage = "<font color='red'>Erro ao Salvar !!!</font>";

	   }  
    
}

//Listar Consultar
String pesq = request.getParameter("submit");

//out.println("submit " + pesq);
if (request.getParameter("submit") != null){

	ww_mensage = "Consultado";
	//out.println("submit   " + request.getParameter("submit") + "<br>");
	String tipo1 = "";
	tipo1 = request.getParameter("campo"); // id
	String tipo2 = "";
	tipo2 = request.getParameter("campo1"); // login
	String tipo3 = "";
	tipo3 = request.getParameter("campo4"); // login

	
	//out.println("campo3   " + request.getParameter("campo4") + "<br>");

	   if (campo2x != "")
	   {   
		   sql3 = "SELECT * FROM tt_ser_01 WHERE id = '" + tipo1 + "'";
	   }
	   if (tipo2 != "")
	   {   
		   sql3 = "SELECT * FROM tt_ser_01 WHERE login LIKE '%" + tipo2 + "%'";
	   }
	   if (tipo3 != "")
	   {   
		   sql3 = "SELECT * FROM tt_ser_01 WHERE nome LIKE '%" + tipo3 + "%'";
	   }
	
}

// Navegacao nos Registros
if (vr1 != null && vr1.equals("navegar1")) {
	
	String inicio_x = "";
    if (request.getParameter("Inicio") != ""){
    	inicio_x = request.getParameter("Inicio");
    	   String Cod_Inicio = inicio_x;
    	    int cod4 =  Integer.parseInt(Cod_Inicio);
        	id_s = cod4 - 1;

    }
    	
    ww_mensage = "Inicio " + id_s + " somado";
	
}
if (vr1 != null && vr1.equals("navegar2")) {
	
	String anterior_x = "";
    if (request.getParameter("Anterior") != ""){
    	anterior_x = request.getParameter("Anterior");
    	   String Cod_Anterior = anterior_x;

    		int cod4 =  Integer.parseInt(Cod_Anterior);
        	id_s = cod4 - 1;
        	if (id_s == 0){
        		id_s = 1;
        	}

    }else{
    	id_s = 1;
    }
 	
    ww_mensage = "Anterior " + id_s + " somado";
	
}
if (vr1 != null && vr1.equals("navegar3")) {
    	
	String proximo_x = "";
    if (request.getParameter("Proximo") != ""){
    	proximo_x = request.getParameter("Proximo");
        String Cod_Proximo = proximo_x;

        int cod4 =  Integer.parseInt(Cod_Proximo);

        id_s = cod4 + 1;
            	
    }else{
    	
    	id_s = 1;
    }
    
    if (id_s == 0){
    	
    	ww_mensage = "Fim do Arquivo "+ id_s;
    	 
    	
    }else{
    	
       ww_mensage = "Proximo " + id_s + " somado";
    }
	
}
if (vr1 != null && vr1.equals("navegar4")) {
	
	String fim_x = "";
    if (request.getParameter("Fim") != ""){
    	fim_x = request.getParameter("Fim");
    	   String Cod_Fim = fim_x;
    	    int cod4 =  Integer.parseInt(Cod_Fim);
        	id_s = cod4 + 1;

    }  	
    ww_mensage = "Fim " + id_s + " somado";
	
}

	// Inicio da Rotina de Apresentação
	
	if (vr1 != null && vr1.equals("navegar1")) {
		
		sql3 = "SELECT * FROM tt_ser_01 ORDER BY id DESC";
		
	}else if (vr1 != null && vr1.equals("navegar2")) {
		
		sql3 = "SELECT * FROM tt_ser_01 WHERE id = '" + id_s + "'";
		
	}else if (vr1 != null && vr1.equals("navegar3")) {
		
		sql3 = "SELECT * FROM tt_ser_01 WHERE id = '" + id_s + "'";
		
	}else if (vr1 != null && vr1.equals("navegar4")) {
		
		sql3 = "SELECT * FROM tt_ser_01 ORDER BY id ASC";	
	}
	
	
	ResultSet res3 = stm.executeQuery(sql3);
	
	while(res3.next()){
		
		campo1x   = res3.getString("id");
		campo2x   = res3.getString("login");
		campo3x   = res3.getString("senha");
		campo4x   = res3.getString("data");
		campo5x   = res3.getString("nome");
		campo6x   = res3.getString("maquina");
		campo7x   = res3.getString("permissao");
		campo8x   = res3.getString("permis2");
		campo9x   = res3.getString("conta");
		campo10x  = res3.getString("programas");
		campo11x  = res3.getString("hora1");
		campo12x  = res3.getString("hora2");
		campo13x  = res3.getString("semana");
		campo14x  = res3.getString("e_mail");
		campo15x  = res3.getString("tipo");

	}	
    // Informa que o Registro nao foi encontrado !!
	if (campo1x == "" || campo1x == null){
		
		String sql3z = "";
		String quardar = "";
		String cons_2 = request.getParameter("submit");
		if (cons_2 != null){
			
		    ww_mensage = "<font color='red'>Registro Não Encontrado!!</font>";
		}    
		
	}	
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<body  style=\" margin-left: 0px;  margin-top: 0px;  margin-right: 0px;  margin-bottom: 0px; \" onkeydown=\"javascript:if (event.KeyCode==13) event.KeyCode=9; javascript:document.onkeydown = keyCatcher();\" onload=\"document.form1.nome_log.focus();\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div align=\"left\">  <table width=\"200\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\r\n");
      out.write("\t    <tr>\r\n");
      out.write("        <td>\r\n");
      out.write("        \r\n");
      out.write("\t    <div align=\"center\">\r\n");
      out.write("            <table width=\"133\" border=\"0\">\r\n");
      out.write("        \r\n");
      out.write("\t\t\t\t<div style=\"Z-INDEX: 600; LEFT: 00px; WIDTH: 616px; POSITION: absolute; TOP: 0px; HEIGHT: 19px\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<IFRAME src=\"user.jsp\" width=\"130\" height=\"22\" scrolling=\"no\" frameborder=\"0\" align=\"left\"></IFRAME>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("        \r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        </td>\r\n");
      out.write("        <td width=\"876\"><div align=\"center\">\r\n");
      out.write("\r\n");
      out.write("        ");
 out.println("<img src='" + sol_1 + "' width=20  height=17  border=0  />"); 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <font face=\"Verdana\" size=\"2\"><b><i>");
 out.println(w_bomdia); 
      out.write("</i></b></font></div></td>\r\n");
      out.write("        <td width=\"7\">&nbsp;</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td><div align=\"center\"><img src=\"imagens/carta.gif\" width=\"40\" height=\"31\"></div></td>\r\n");
      out.write("\t      <td><table width=\"200\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t        <tr>\r\n");
      out.write("\t        \r\n");
      out.write("\t        \r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"3\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/cadastro.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"4\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/contribuicao.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"4\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/relatorios.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"4\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/saude.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"4\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/juridico.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"4\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/caixa.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"4\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/website.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"4\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/operador.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"4\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/help.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"3\" height=\"30\"></td>\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("        </tr>\t\t\t\r\n");
      out.write("\t      </table></td>\r\n");
      out.write("\t            <td>&nbsp;</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td>&nbsp;</td>\r\n");
      out.write("        <td align=\"left\" valign=\"top\"><font color=\"#000000\" size=\"1\">");
 out.println(w_versaox); 
      out.write("</font></td>\r\n");
      out.write("        <td>&nbsp;</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td>&nbsp;</td>\r\n");
      out.write("        <td align=\"left\" valign=\"top\">\r\n");
      out.write("        <!--  Inicio do Form -->\r\n");
      out.write("        <div align=\"center\">\r\n");
      out.write("          <table width=\"711\" border=\"16\" bordercolor=\"#5A9CB1\" bgcolor=\"#FFFFFF\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td><div align=\"center\">\r\n");
      out.write("                  <table width=\"100%\" border=\"0\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td width=\"64%\" height=\"42\"><div align=\"left\"><b><font size=\"5\" face=\"Verdana\" color=\"#5A9CB1\"><img src=\"imagens/px1.gif\" width=\"10\" height=\"10\">Cadastro de Permiss&otilde;es </font></b></div></td>\r\n");
      out.write("                      <td width=\"36%\"><div align=\"center\"><b><font size=\"2\" face=\"Verdana\">");
 out.println(ww_mensage); 
      out.write("</font></b></div></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  </table>\r\n");
      out.write("              </div></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr valign=\"top\">\r\n");
      out.write("              <td valign=\"top\"><div align=\"center\">\r\n");
      out.write("                <form name=\"form1\" method=\"post\" action=\"cad_senha.jsp\">\r\n");
      out.write("                  <table width=\"100%\" border=\"0\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td height=\"9\"><div align=\"center\">\r\n");
      out.write("                        <table width=\"100%\" border=\"0\" cellpadding=\"0\">\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td width=\"19%\"><div align=\"right\"><b><font size=\"2\" face=\"Verdana\">Login.:</font></b></div></td>\r\n");
      out.write("                            <td width=\"27%\"><input name=\"campo1\" type=\"text\" id=\"campo1\" value=\"");
 out.println(campo2x); 
      out.write("\" style=\" font-family: Verdana; font-size: 14px;  height:23px;width:156px;  \" onfocus=\"this.className='anormal'\"  onblur=\"this.className='normal'\" value=\"\" >\r\n");
      out.write("                                             <input name=\"campo\" type=\"hidden\" id=\"campo\" value=\"");
 out.println(campo1x); 
      out.write("\">\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td width=\"10%\"><div align=\"right\"><b><font size=\"2\" face=\"Verdana\">Senha.:</font></b></div></td>\r\n");
      out.write("                            <td width=\"18%\"><input name=\"campo2\" type=\"password\" id=\"campo2\" value=\"");
 out.println(campo3x); 
      out.write("\" style=\" font-family: Verdana; font-size: 14px;  height:23px;width:106px;  \" onfocus=\"this.className='anormal'\"  onblur=\"this.className='normal'\" value=\"\" ></td>\r\n");
      out.write("                            <td width=\"10%\"><div align=\"right\"><b><font size=\"2\" face=\"Verdana\">Data.:</font></b></div></td>\r\n");
      out.write("                            <td width=\"16%\"><input name=\"campo3\" type=\"text\" id=\"campo3\" value=\"");
 out.println(campo4x); 
      out.write("\" style=\" font-family: Verdana; font-size: 14px;  height:23px;width:95px;  \" onfocus=\"this.className='anormal'\"  onblur=\"this.className='normal'\" value=\"\" ></td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                        <table width=\"100%\" border=\"0\" cellpadding=\"0\">\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td width=\"19%\"><div align=\"right\"><b><font size=\"2\" face=\"Verdana\">Nome.:</font></b></div></td>\r\n");
      out.write("                            <td width=\"47%\"><input name=\"campo4\" type=\"text\" id=\"campo4\" value=\"");
 out.println(campo5x); 
      out.write("\" style=\" font-family: Verdana; font-size: 14px;  height:23px;width:296px;  \" onfocus=\"this.className='anormal'\"  onblur=\"this.className='normal'\" value=\"\" ></td>\r\n");
      out.write("                            <td width=\"12%\"><div align=\"right\"><b><font size=\"2\" face=\"Verdana\">Maquina.:</font></b></div></td>\r\n");
      out.write("                            <td width=\"22%\"><input name=\"campo5\" type=\"text\" id=\"campo5\" value=\"");
 out.println(campo6x); 
      out.write("\" style=\" font-family: Verdana; font-size: 14px;  height:23px;width:135px;  \" onfocus=\"this.className='anormal'\"  onblur=\"this.className='normal'\" value=\"\" ></td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                        <table width=\"100%\" border=\"0\" cellpadding=\"0\">\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td width=\"19%\"><div align=\"right\"><b><font size=\"2\" face=\"Verdana\">Permiss&atilde;o.:</font></b></div></td>\r\n");
      out.write("                            <td width=\"26%\"><input name=\"campo6\" type=\"text\" id=\"campo6\" value=\"");
 out.println(campo7x); 
      out.write("\" style=\" font-family: Verdana; font-size: 14px;  height:23px;width:156px;  \" onfocus=\"this.className='anormal'\"  onblur=\"this.className='normal'\" value=\"\" ></td>\r\n");
      out.write("                            <td width=\"11%\"><div align=\"right\"><b><font size=\"2\" face=\"Verdana\">Nivel.:</font></b></div></td>\r\n");
      out.write("                            <td width=\"12%\"><input name=\"campo7\" type=\"text\" id=\"campo7\" value=\"");
 out.println(campo8x); 
      out.write("\" style=\" font-family: Verdana; font-size: 14px;  height:23px;width:52px;  \" onfocus=\"this.className='anormal'\"  onblur=\"this.className='normal'\" value=\"\" ></td>\r\n");
      out.write("                            <td width=\"10%\"><div align=\"right\"><b><font size=\"2\" face=\"Verdana\">Conta.:</font></b></div></td>\r\n");
      out.write("                            <td width=\"22%\"><select name=\"campo8\" type=\"text\" id=\"campo8\" value=\"");
 out.println(campo9x); 
      out.write("\" style=\" font-family: Verdana; font-size: 14px;  height:23px;width:134px;  \" onfocus=\"this.className='anormal'\"  onblur=\"this.className='normal'\" value=\"\" >\r\n");
      out.write("                            \r\n");
      out.write("                            ");


							if (campo9x != null || campo9x != "")
							{
							
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"");
 out.println(campo9x); 
      out.write('"');
      out.write('>');
      out.write(' ');
 out.println(campo9x); 
      out.write(" </option>\r\n");
      out.write("\t\t\t\t\t\t\t            <option value=\"BLOQUEADA\">  BLOQUEADA     </option>\r\n");
      out.write("\t\t\t\t\t\t\t            <option value=\"ATIVA\">      ATIVA </option>\r\n");
      out.write("\t\t\t\t\t\t\t            <option value=\"CANCELADA\">  CANCELADA  </option>\r\n");
      out.write("\t\t\t\t\t\t\t");
	
							}else{
							
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t            <option value=\" \">  </option>\r\n");
      out.write("\t\t\t\t\t\t\t            <option value=\"BLOQUEADA\">  BLOQUEADA     </option>\r\n");
      out.write("\t\t\t\t\t\t\t            <option value=\"ATIVA\">      ATIVA </option>\r\n");
      out.write("\t\t\t\t\t\t\t            <option value=\"CANCELADA\">  CANCELADA  </option>\r\n");
      out.write("\t\t\t\t\t\t\t");
            
							}
	                        
      out.write("\r\n");
      out.write("                            </select>\r\n");
      out.write("                            \r\n");
      out.write("                            </td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                        <table width=\"100%\" border=\"0\" cellpadding=\"0\">\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td width=\"19%\" valign=\"top\"><div align=\"right\"><b><font size=\"2\" face=\"Verdana\">Programas Permitidos .:</font></b></div></td>\r\n");
      out.write("                            <td width=\"81%\"><textarea name=\"campo9\" cols=\"55\" rows=\"5\" id=\"campo9\" style=\" font-family: Verdana; font-size: 14px;  width:514px;  \" onfocus=\"this.className='anormal'\"  onblur=\"this.className='normal'\" >");
 out.println(campo10x); 
      out.write("</textarea></td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                        <table width=\"100%\" border=\"0\" cellpadding=\"0\">\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td width=\"19%\">&nbsp;</td>\r\n");
      out.write("                            <td width=\"20%\"><div align=\"center\"><b><font size=\"2\" face=\"Verdana\">Inicio</font></b></div></td>\r\n");
      out.write("                            <td width=\"16%\"><div align=\"center\"><b><font size=\"2\" face=\"Verdana\">Fim</font></b></div></td>\r\n");
      out.write("                            <td width=\"11%\">&nbsp;</td>\r\n");
      out.write("                            <td width=\"34%\"><div align=\"center\"><b><font size=\"2\" face=\"Verdana\">Dias da Semana </font></b></div></td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td><div align=\"right\"><b><font size=\"2\" face=\"Verdana\">Horario.:</font></b></div></td>\r\n");
      out.write("                            <td><input name=\"campo10\" type=\"text\" id=\"campo10\" value=\"");
 out.println(campo11x); 
      out.write("\" style=\" font-family: Verdana; font-size: 14px;  height:23px;width:95px;  \" onfocus=\"this.className='anormal'\"  onblur=\"this.className='normal'\" value=\"\" >\r\n");
      out.write("                              <strong><font size=\"2\" face=\"Verdana\">as:</font></strong> </td>\r\n");
      out.write("                            <td><input name=\"campo11\" type=\"text\" id=\"campo11\" value=\"");
 out.println(campo12x); 
      out.write("\" style=\" font-family: Verdana; font-size: 14px;  height:23px;width:91px;  \" onfocus=\"this.className='anormal'\"  onblur=\"this.className='normal'\" value=\"\" ></td>\r\n");
      out.write("                            <td><b><font size=\"2\" face=\"Verdana\">Semana:</font></b></td>\r\n");
      out.write("                            <td><input name=\"campo12\" type=\"text\" id=\"campo12\" value=\"");
 out.println(campo13x); 
      out.write("\" style=\" font-family: Verdana; font-size: 14px;  height:23px;width:210px;  \" onfocus=\"this.className='anormal'\"  onblur=\"this.className='normal'\" value=\"\" ></td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                        <table width=\"100%\" border=\"0\" cellpadding=\"0\">\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td width=\"19%\"><div align=\"right\"><b><font size=\"2\" face=\"Verdana\">E-mail.:</font></b></div></td>\r\n");
      out.write("                            <td width=\"36%\"><input name=\"campo13\" type=\"text\" id=\"campo13\" value=\"");
 out.println(campo14x); 
      out.write("\" style=\" font-family: Verdana; font-size: 14px;  height:23px;width:224px;  \" onfocus=\"this.className='anormal'\"  onblur=\"this.className='normal'\" value=\"\" ></td>\r\n");
      out.write("                            <td width=\"11%\"><div align=\"right\"><b><font size=\"2\" face=\"Verdana\">Tipo.:</font></b></div></td>\r\n");
      out.write("                            <td width=\"34%\"><select name=\"campo14\" type=\"text\" id=\"campo14\" value=\"");
 out.println(campo15x); 
      out.write("\" style=\" font-family: Verdana; font-size: 14px;  height:23px;width:210px;  \" onfocus=\"this.className='anormal'\"  onblur=\"this.className='normal'\" value=\"\" >\r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            ");


							if (campo15x != null || campo15x != "")
							{
							
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"");
 out.println(campo15x); 
      out.write('"');
      out.write('>');
      out.write(' ');
 out.println(campo15x); 
      out.write(" </option>\r\n");
      out.write("\t\t\t\t\t\t\t            <option value=\"ADMINISTRADOR\">  ADMINISTRADOR </option>\r\n");
      out.write("\t\t\t\t\t\t\t            <option value=\"OP. DE CAIXA\">   OP. DE CAIXA  </option>\r\n");
      out.write("\t\t\t\t\t\t\t            <option value=\"USUARIO\">  USUARIO </option>\r\n");
      out.write("\t\t\t\t\t\t\t");
	
							}else{
							
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t            <option value=\" \">  </option>\r\n");
      out.write("\t\t\t\t\t\t\t            <option value=\"ADMINISTRADOR\">  ADMINISTRADOR </option>\r\n");
      out.write("\t\t\t\t\t\t\t            <option value=\"OP. DE CAIXA\">   OP. DE CAIXA  </option>\r\n");
      out.write("\t\t\t\t\t\t\t            <option value=\"USUARIO\">  USUARIO </option>\r\n");
      out.write("\t\t\t\t\t\t\t");
            
							}
	                        
      out.write("\r\n");
      out.write("                            </select>\r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            </td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("\r\n");
      out.write("                        <table width=\"100%\" border=\"0\" cellpadding=\"0\">\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td width=\"19%\" align=\"left\">&nbsp;</td>\r\n");
      out.write("                            <td width=\"36%\" align=\"left\"><input type=\"image\" name=\"resetarsenha\" value=\"resetarsenha\" src=\"imagens/resetsenha.png\" />\r\n");
      out.write("                                                         </td>\r\n");
      out.write("                            <td width=\"11%\">&nbsp;</td>\r\n");
      out.write("                            <td width=\"34%\">&nbsp;</td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                      </div></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  </table>\r\n");
      out.write("                  <img src=\"imagens/px1.gif\" width=\"10\" height=\"4\">\r\n");
      out.write("                  \r\n");
      out.write("                  <table width=\"633\"  height=\"80\" border=\"0\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td width=\"4\"><img src=\"imagens/px1.gif\" width=\"15\" height=\"1\"></td>\r\n");
      out.write("                      <td width=\"590\"><div align=\"center\">\r\n");
      out.write("                          <!-- Inicio do Botoes de chamada -->\r\n");
      out.write("                          <table width=\"590\" border=\"0\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                            <td width=\"92\"><div align=\"center\">\r\n");
      out.write("                    ");

					if (per4.equals("SIM")){
					
      out.write("\r\n");
      out.write(" \r\n");
      out.write("                              <a href=\"permissao.jsp?Cod_2=");
 out.println(campo2x); 
      out.write("\" ><img src=\"imagens/botaoazul46.PNG\" width=\"92\" height=\"22\" border=\"0\"></a>\r\n");
      out.write("                    ");

                    }else{
					
      out.write("\r\n");
      out.write("                                  <img src=\"imagens/botaoazul46.PNG\" width=\"92\" height=\"22\" border=\"0\">\r\n");
      out.write("                    ");

					}
                    
      out.write("\r\n");
      out.write("                              </div></td>          \r\n");
      out.write("                              <td width=\"92\"><div align=\"center\"><a href=\"cad_senha.jsp?opcao=lis_grid&Cod_2=");
 out.println(campo1x); 
      out.write("\" ><img src=\"imagens/botaoazul3.PNG\" width=\"92\" height=\"22\" border=\"0\"></a></div></td>\r\n");
      out.write("                              <td width=\"92\"><div align=\"center\">\r\n");
      out.write("                                  ");

					
					
					if (per3.equals("SIM")){
					
      out.write("\r\n");
      out.write("                                  <a href=\"cad_senha.jsp?opcao=excluir&Cod_2=");
 out.println(campo1x); 
      out.write("\"> <img src=\"imagens/botaoazul4.PNG\" width=\"92\" height=\"22\" border=\"0\"></a>\r\n");
      out.write("                                  ");

					}else{
					
      out.write("\r\n");
      out.write("                                  <img src=\"imagens/botaoazul01.PNG\" width=\"92\" height=\"22\" border=\"0\">\r\n");
      out.write("                                  ");

					}
					
      out.write("\r\n");
      out.write("                              </div></td>\r\n");
      out.write("                              <td width=\"92\"><div align=\"center\">\r\n");
      out.write("                                  ");

					if (per2.equals("SIM")){
					
      out.write("\r\n");
      out.write("                                  <input type=\"image\" name=\"alterar\" value=\"alterar\" src=\"imagens/botaoazul5.PNG\" />\r\n");
      out.write("                                  \r\n");
      out.write("                                  ");

					}else{
					
      out.write("\r\n");
      out.write("                                  <img src=\"imagens/botaoazul01.PNG\" width=\"92\" height=\"22\" border=\"0\">\r\n");
      out.write("                                  ");

					}
                    
      out.write("\r\n");
      out.write("                              </div></td>\r\n");
      out.write("                              <td width=\"92\"><div align=\"center\">\r\n");
      out.write("                                  ");

					if (per1.equals("SIM")){
						
						
						            if (campo1x == "" || campo1x == null){
					
      out.write("\r\n");
      out.write("                                  \r\n");
      out.write("                                        <input type=\"image\" name=\"incluir\" value=\"incluir\" src=\"imagens/botaoazul10.PNG\" />\r\n");
      out.write("                                    ");

						            }else{
						            
      out.write("\r\n");
      out.write("\t\t\t\t\t\t            \t<img src=\"imagens/botaoazul01.PNG\" width=\"92\" height=\"22\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t            ");
	
						            }
					}else{
					
      out.write("\r\n");
      out.write("                                  <img src=\"imagens/botaoazul01.PNG\" width=\"92\" height=\"22\" border=\"0\">\r\n");
      out.write("                                  ");
	
					}
                    
      out.write("\r\n");
      out.write("                              </div></td>\r\n");
      out.write("                              <td width=\"200\"><div align=\"center\">\r\n");
      out.write("                              \r\n");
      out.write("                              <input type=\"image\" name=\"submit\" value=\"pesquisa\" src=\"imagens/botaoazul7.PNG\" />   \r\n");
      out.write("\r\n");
      out.write("                                 \r\n");
      out.write("                              \r\n");
      out.write("                              \r\n");
      out.write("                              \r\n");
      out.write("                              </div></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                              <td><div align=\"center\">\r\n");
      out.write("                                  <table width=\"89\" border=\"0\" cellpadding=\"1\" cellspacing=\"0\">\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                      <td width=\"39\"><a href=\"cad_senha.jsp?opcao=navegar1&Inicio=");
 out.println(campo1x); 
      out.write("\" ><img src=\"imagens/inicio.PNG\" width=\"39\" height=\"32\" border=\"0\"></a></td>\r\n");
      out.write("                                      <td width=\"94\"><a href=\"cad_senha.jsp?opcao=navegar2&Anterior=");
 out.println(campo1x); 
      out.write("\" ><img src=\"imagens/anterior.PNG\" width=\"39\" height=\"32\" border=\"0\"></a></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                  </table>\r\n");
      out.write("                              </div></td>\r\n");
      out.write("                              <td><div align=\"center\">\r\n");
      out.write("                                  <table width=\"76\" border=\"0\" cellpadding=\"1\" cellspacing=\"0\">\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                      <td width=\"40\"><a href=\"cad_senha.jsp?opcao=navegar3&Proximo=");
 out.println(campo1x); 
      out.write("\" ><img src=\"imagens/proximo.PNG\" width=\"40\" height=\"32\" border=\"0\"></a></td>\r\n");
      out.write("                                      <td width=\"26\"><a href=\"cad_senha.jsp?opcao=navegar4&Fim=");
 out.println(campo1x); 
      out.write("\"><img src=\"imagens/fim.PNG\" width=\"39\" height=\"32\" border=\"0\"></a></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                  </table>\r\n");
      out.write("                              </div></td>\r\n");
      out.write("                              <td><div align=\"center\"><a href=\"#\" target=\"new\" ><img src=\"imagens/botaoazul01.PNG\" width=\"92\" height=\"22\" border=\"0\"></a></div></td>\r\n");
      out.write("                              <td><div align=\"center\"><a href=\"#\" target=\"new\" ><img src=\"imagens/botaoazul01.PNG\" width=\"92\" height=\"22\" border=\"0\"></a></div></td>\r\n");
      out.write("                              <td>\r\n");
      out.write("                              \r\n");
      out.write("                                 <input type=\"image\" name=\"limpar\" value=\"limpar\" src=\"imagens/botaobanco51.png\" />   \r\n");
      out.write("                              \r\n");
      out.write("                              \r\n");
      out.write("                              \r\n");
      out.write("                              </div></td>\r\n");
      out.write("                              <td><div align=\"center\"><a href=\"menu1.jsp\"><img src=\"imagens/botaoazul24.PNG\" width=\"92\" height=\"22\" border=\"0\"></a></div></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                          </table>\r\n");
      out.write("                          <!--  Fim dos Botoes de chamada -->\r\n");
      out.write("                      </div></td>\r\n");
      out.write("                      <td width=\"33\" valign=\"bottom\"><img src=\"imagens/vacina.JPG\" width=\"27\" height=\"38\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  </table>\r\n");
      out.write("                  </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("</div>\r\n");
      out.write("        <!-- Fim do Form -->\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>&nbsp;</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("\r\n");
      out.write("\t  </table>\r\n");
      out.write("\t  <br/>\r\n");
      out.write("\t  <br/>\r\n");
      out.write("\t  <br/>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <div align=center>\r\n");
      out.write("\t  \r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("\t\r\n");
      out.write("</html>\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
