/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2013-03-11 01:56:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;
import java.text.*;
import java.sql.*;

public final class erroh_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/config.jsp", Long.valueOf(1362954014485L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("\r\n");
      out.write("//document.onkeydown = keyCatcher;\r\n");
      out.write("\r\n");
      out.write("function keyCatcher() \r\n");
      out.write("{\r\n");
      out.write("   var e = event.srcElement.tagName;\r\n");
      out.write("\r\n");
      out.write("   if (event.keyCode == 8 && e != \"INPUT\" && e != \"TEXTAREA\") \r\n");
      out.write("   {\r\n");
      out.write("      event.cancelBubble = true;\r\n");
      out.write("      event.returnValue = false;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   if (event.keyCode == 27) \r\n");
      out.write("   {\r\n");
      out.write("\t\twindow.location=\"\";\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("window.focus();\r\n");
      out.write("document.form1.nome_log.focus();\r\n");
      out.write("\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".normal {\r\n");
      out.write("\t\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("}\r\n");
      out.write(".anormal {\r\n");
      out.write("\t\tbackground-color: Lavender;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

// Titulo do Sistema
String w_titulo   = "Sistema JSP";
String w_versaox  = "Atualizado em 10/03/2013 às 17:12";

// Variaveis Banco de Dados
String driver_pes     = "com.mysql.jdbc.Driver";
String db_dados_pes   = "agenda";
String connection_pes = "jdbc:mysql://localhost:3306/" + db_dados_pes;
String user_pes       = "root";
String password_pes   = "12345";



      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Sistema XP</title>\r\n");
      out.write("<link rel='shortcut icon' href='imagens/favicon.ico'>\r\n");
      out.write("\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"menu.css\"/>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\r\n");
      out.write("background-image: url('imagens/logosys.jpg');\r\n");
      out.write("background-attachment: fixed\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".normal {\r\n");
      out.write("\t\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("}\r\n");
      out.write(".anormal {\r\n");
      out.write("\t\tbackground-color: Lavender;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\"><!--\r\n");
      out.write("\r\n");
      out.write("document.onkeydown = keyCatcher;\r\n");
      out.write("\r\n");
      out.write("function keyCatcher() \r\n");
      out.write("{\r\n");
      out.write("   var e = event.srcElement.tagName;\r\n");
      out.write("\r\n");
      out.write("   if (event.keyCode == 8 && e != \"INPUT\" && e != \"TEXTAREA\") \r\n");
      out.write("   {\r\n");
      out.write("      event.cancelBubble = true;\r\n");
      out.write("      event.returnValue = false;\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");

// Rotinas Principais

// config.jsp
// login.jsp
// logar.jsp
// menu1.jsp


      out.write("\r\n");
      out.write("\r\n");


String situa_1 = "";
String w_nome3 = "";
String sol_1   = "";

//Cria Variavel de sessao
String objeto = "";
// Grava informacoa na sessao
session.setAttribute("minha_sessao1", objeto);

//Resgata informacao gravada na sessao
String Minha_sessao1 = (String) session.getAttribute("minha_sessao1");

if (Minha_sessao1 != null){
	w_nome3 = Minha_sessao1;
}

//Saldação ao usuario

int w_Hora = Integer.parseInt((new java.text.SimpleDateFormat("HH")).format(new java.util.Date()));

String w_AMPM = new java.text.SimpleDateFormat("a").format(new java.util.Date());
String w_SEMA = new java.text.SimpleDateFormat("EEEE").format(new java.util.Date());

if (w_Hora > 0 && w_Hora <= 6) {
    situa_1 = "Boa Madrugada";
    sol_1   = "imagens/noite.png";
    
}
if (w_Hora > 6 && w_Hora <= 12) {
    situa_1 = "Bom Dia";
    sol_1   = "imagens/dia.png";
    
}
if (w_Hora > 12 && w_Hora <= 18) {
    situa_1 = "Boa Tarde";
    sol_1   = "imagens/dia.png";
    
}
if (w_Hora >= 19 && w_Hora <= 23) {
    situa_1 = "Boa Noite";
    sol_1   = "imagens/noite.png";
    
}

String w_bomdia = situa_1 + " Seja Bem Vindo, " + w_nome3 + " hoje e, " + new java.text.SimpleDateFormat("EEEE dd 'de' MMMM 'de' yyyy").format(new java.util.Date()) + "<br />";
String w_hora_acesso = new java.text.SimpleDateFormat("HH:mm").format(new java.util.Date());


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<body  style=\" margin-left: 0px;  margin-top: 0px;  margin-right: 0px;  margin-bottom: 0px; \" onkeydown=\"javascript:if (event.KeyCode==13) event.KeyCode=9; javascript:document.onkeydown = keyCatcher();\" onload=\"document.form1.nome_log.focus();\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div align=\"left\">  <table width=\"200\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\r\n");
      out.write("\t    <tr>\r\n");
      out.write("        <td><div align=\"center\">\r\n");
      out.write("          <table width=\"133\" border=\"0\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"127\">                <div align=\"center\"><font color=\"#339999\" size=\"2\">1 usu&aacute;rio(s) on-line </font></div></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td><div align=\"center\"><img src=\"imagens/kitt.gif\" width=\"65\" height=\"4\"></div></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("        </div></td>\r\n");
      out.write("        <td width=\"876\"><div align=\"center\">\r\n");
      out.write("\r\n");
      out.write("        ");
 out.println("<img src='" + sol_1 + "' width=20  height=17  border=0  />"); 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <font face=\"Verdana\" size=\"2\"><b><i>");
 out.println(w_bomdia); 
      out.write("</i></b></font></div></td>\r\n");
      out.write("        <td width=\"7\">&nbsp;</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td><div align=\"center\"><img src=\"imagens/carta.gif\" width=\"40\" height=\"31\"></div></td>\r\n");
      out.write("\t      <td><table width=\"200\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t        <tr>\r\n");
      out.write("\t        \r\n");
      out.write("\t        \r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"3\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/cadastro.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"4\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/contribuicao.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"4\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/relatorios.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"4\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/saude.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"4\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/juridico.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"4\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/caixa.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"4\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/website.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"4\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/operador.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"4\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/help.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"3\" height=\"30\"></td>\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("        </tr>\t\t\t\r\n");
      out.write("\t      </table></td>\r\n");
      out.write("\t            <td>&nbsp;</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td>&nbsp;</td>\r\n");
      out.write("        <td align=\"left\" valign=\"top\"><font color=\"#000000\" size=\"1\">");
 out.println(w_versaox); 
      out.write("</font></td>\r\n");
      out.write("        <td>&nbsp;</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td>&nbsp;</td>\r\n");
      out.write("        <td align=\"left\" valign=\"top\">\r\n");
      out.write("        <!--  Inicio do Form -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <br><br><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t <div align=center>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<table align=center border='15' bgcolor='#FFF8DC' bordercolor ='#5A9CB1'>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=center>\r\n");
      out.write("\t\t\t\t\t\t\t     <font color = #FF0000><b>&nbsp;&nbsp; ERRO ACESSO NÃO PERMITIDO !!!&nbsp;&nbsp;</font><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t                     &nbsp;&nbsp;Seu computador não tem permissão,<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t &nbsp;&nbsp;para uso neste horario, ");
 out.println(w_hora_acesso); 
      out.write(" caso<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t                     &nbsp;&nbsp;seja nessessario entre em contato com o<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t ADMINISTRADOR DO SISTEMA<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t </b>\r\n");
      out.write("\t\t\t\t\t\t\t<table align=center>\r\n");
      out.write("\t\t\t\t\t\t\t<form method='POST' action='login.jsp'>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=image name='consulta' src='imagens/botao_voltar.PNG'></td>\r\n");
      out.write("\t\t\t\t\t\t\t</form>  \r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("\t\r\n");
      out.write("        <!-- Fim do Form -->\r\n");
      out.write("        </td>\r\n");
      out.write("        \r\n");
      out.write("      </tr>\r\n");
      out.write("\r\n");
      out.write("\t  </table>\r\n");
      out.write("\t  <br/>\r\n");
      out.write("\t  <br/>\r\n");
      out.write("\t  <br/>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <div align=center>\r\n");
      out.write("\t  \r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("\t\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
