/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2013-06-18 18:37:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\r\n");

// Cria Variavel de sessao
String objeto = "holodek";
// Grava informacoa na sessao
session.setAttribute("minha_sessao1", objeto);
// Resgata informacao gravada na sessao
String Minha_sessao1 = (String) session.getAttribute("minha_sessao1");
// Mostra na tela conteudo da sessao
out.println("Usuario: <font color='#FF0000'>" + Minha_sessao1 + "</font>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>Agenda Telefonica</title>\r\n");
      out.write("<link rel='shortcut icon' href='imagens/favicon.ico'>\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\r\n");
      out.write("background-image: url('imagens/logosys.jpg');\r\n");
      out.write("background-attachment: fixed\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<br>\r\n");


String nome1 = request.getParameter("nome1");   
String id1 = request.getParameter("id1");   
String telefone1 = request.getParameter("telefone1");   


      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<p align=\"center\"><font color=\"#009933\"><strong><font face=\"Verdana\">Cadastro de Contatos em Java MySQL</font> </strong></font></p>\r\n");
      out.write("\r\n");
      out.write("<form action=\"cadastrar.jsp\" method=\"post\" name=\"form2\">\r\n");
      out.write("\r\n");
      out.write("<table width=\"329\" border=\"0\" align=\"center\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"32\"><div align=\"right\"><strong><font size=\"3\" face=\"Verdana\">Codigo:</font></strong></div></td>\r\n");
      out.write("    <td width=\"177\"><input type=\"text\" name=\"id\" value=\"");
      out.print( id1 );
      out.write("\"></td>\r\n");
      out.write("    <td width=\"40\">&nbsp;</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"33\"><div align=\"right\"><strong><font size=\"3\" face=\"Verdana\">Nome:</font></strong></div></td>\r\n");
      out.write("    <td><input type=\"text\" name=\"nome\" value=\"");
      out.print( nome1 );
      out.write("\"></td>\r\n");
      out.write("    <td>&nbsp;</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><div align=\"right\"><strong><font size=\"3\" face=\"Verdana\">Telefone:</font></strong></div></td>\r\n");
      out.write("    <td><input type=\"text\" name=\"telefone\" value=\"");
      out.print( telefone1 );
      out.write("\"></td>\r\n");
      out.write("    <td>&nbsp;</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("<div align=\"center\"><br>\r\n");
      out.write("\r\n");
      out.write("<table width=\"30%\" border=\"0\" align=\"center\" cellspacing=\"2\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"33%\"><div align=\"center\"><a href=\"cadastrar.jsp\"><img src=\"imagens/botaoazul6.PNG\" width=\"92\" height=\"22\" border=\"0\"></a></div></td>\r\n");
      out.write("    <td width=\"33%\"><div align=\"center\"><a href=\"excluir.jsp\"><img src=\"imagens/botaoazul4.PNG\" width=\"92\" height=\"22\" border=\"0\"></a></div></td>\r\n");
      out.write("    <td width=\"34%\"><div align=\"center\"><a href=\"consultar.jsp\"><img src=\"imagens/botaoazul7.PNG\" width=\"92\" height=\"22\" border=\"0\"></a></div></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("       </form> \r\n");
      out.write(" \r\n");
      out.write("<div align=\"center\"></div>\r\n");
      out.write("\r\n");

// Para destruir uma sessao = session.invalidade();

String driver     = "com.mysql.jdbc.Driver";
String db_dados   = "agenda";
String connection = "jdbc:mysql://localhost:3306/" + db_dados;
String user       = "root";
String password   = "12345";
Class.forName(driver);
Connection Con = DriverManager.getConnection(connection, user, password);
Statement stm = Con.createStatement();

String var2 = "Edson de Araujo";

ResultSet res = stm.executeQuery("SELECT * FROM registros");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("<table width=\"510\" border=\"1\" align=\"center\">\r\n");
      out.write("\r\n");
      out.write("<td width=\"71\"><strong>Codigo</strong></td>\r\n");
      out.write("<td width=\"299\"><strong>Nome</strong></td>\r\n");
      out.write("<td width=\"118\"><strong>Telefone</strong></td>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\r\n");

while(res.next()){

      out.write("\r\n");
      out.write("<td align=\"center\">");
out.println(res.getString("id"));
      out.write("</td>\r\n");
      out.write("<td align=\"left\">");
out.println(res.getString("nome"));
      out.write("</td>\r\n");
      out.write("<td align=\"left\">");
out.println(res.getString("telefone"));
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");

}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
