/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2013-03-11 02:12:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.*;
import java.sql.*;

public final class logar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/config.jsp", Long.valueOf(1362954014485L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

// Titulo do Sistema
String w_titulo   = "Sistema JSP";
String w_versaox  = "Atualizado em 10/03/2013 às 17:12";

// Variaveis Banco de Dados
String driver_pes     = "com.mysql.jdbc.Driver";
String db_dados_pes   = "agenda";
String connection_pes = "jdbc:mysql://localhost:3306/" + db_dados_pes;
String user_pes       = "root";
String password_pes   = "12345";



      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Sistema XP</title>\r\n");
      out.write("<link rel='shortcut icon' href='imagens/favicon.ico'>\r\n");
      out.write("\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"menu.css\"/>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\r\n");
      out.write("background-image: url('imagens/logosys.jpg');\r\n");
      out.write("background-attachment: fixed\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".normal {\r\n");
      out.write("\t\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("}\r\n");
      out.write(".anormal {\r\n");
      out.write("\t\tbackground-color: Lavender;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\"><!--\r\n");
      out.write("\r\n");
      out.write("document.onkeydown = keyCatcher;\r\n");
      out.write("\r\n");
      out.write("function keyCatcher() \r\n");
      out.write("{\r\n");
      out.write("   var e = event.srcElement.tagName;\r\n");
      out.write("\r\n");
      out.write("   if (event.keyCode == 8 && e != \"INPUT\" && e != \"TEXTAREA\") \r\n");
      out.write("   {\r\n");
      out.write("      event.cancelBubble = true;\r\n");
      out.write("      event.returnValue = false;\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");

// Rotinas Principais

// config.jsp
// login.jsp
// logar.jsp
// menu1.jsp


      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");


String nome_user     = request.getParameter("nome_log");
String senha_user    = request.getParameter("pwd");
String w_acao        = request.getParameter("acao");

//String w_acao = (String) (request.getParameter("acao"));

String sql1 = "";
String sql2 = "";
String msg  = "";
String msg1 = "";
String msg2 = "";
String msg3 = "";
String msg4 = "";
String msg5 = "";
String msg6 = "";
String msg7 = "";


Class.forName(driver_pes);
Connection Con2 = DriverManager.getConnection(connection_pes, user_pes, password_pes);

Statement stm2 = Con2.createStatement();

//Busca Usuario
sql1 = "SELECT * FROM tt_ser_01 WHERE login = '" + nome_user.toUpperCase() + "' AND senha = md5('" + senha_user + "')";

ResultSet res2 = stm2.executeQuery(sql1);

while(res2.next()){

		msg   = res2.getString("login");
		msg1  = res2.getString("senha");
		msg2  = res2.getString("e_mail");
		msg3  = res2.getString("programas");
		msg4  = res2.getString("tipo");
		msg5  = res2.getString("semana");
		msg6  = res2.getString("hora1");
		msg7  = res2.getString("hora2");


}
    
//out.println("msg "  + msg + "<br>");
//out.println("msg1 " + msg1 + "<br>");
//out.println("msg2 " + msg2 + "<br>");
//out.println("msg3 " + msg3 + "<br>");
//out.println("msg4 " + msg4 + "<br>");
//out.println("msg5 " + msg5 + "<br>");

if (msg4 != null && msg4 != ""){


	// Verifica Permissao para Horario
	int w_atual = Integer.parseInt((new java.text.SimpleDateFormat("HH")).format(new java.util.Date()));

	String h_inicio = msg6;  
	h_inicio        = h_inicio.substring(0,2);
	int h_inicioh   = Integer.parseInt(h_inicio);

	String h_fim    = msg7;  
	h_fim           = h_fim.substring(0,2);
	int h_fimh      = Integer.parseInt(h_fim);
	   

	if(w_atual >=  h_inicioh && w_atual <=  h_fimh){
		
		//out.println("Voce tem premissao de uso as "  + w_atual + "<br>");

		// OK
	}else{
		
		
		{response.sendRedirect("erroh.jsp");}
		
	}

	
	// Rotina Verifica dia da Semana e Permissao da Tela 

	String p_AMPM = new java.text.SimpleDateFormat("EEE").format(new java.util.Date());
	String str = msg5;
	String[] b = str.split(",");
	int faz = 0;

	for (int i= 0; i<=b.length-1; i++){	
			if (p_AMPM.toUpperCase().equals(b[i])){
				faz = 4;
			}
	}

	
	// Fim Verificar dia da Semana e Permissao da Tela 

	
	if (faz == 4){
		//OK

		if (msg == "" && msg1 == "")
		{
			//Menssagens = "Registro não Encontrado !!!!";
			{response.sendRedirect("login.jsp?login=falhou");}
			//out.println("entrei no 1 <br>");
			
			   
		}else{
		
			
			// Cria Variavel de sessao
			String objeto = msg;
			// Grava informacoa na sessao
			session.setAttribute("minha_sessao1", objeto);
		
			if(w_acao != null && w_acao.equals("logar")){    
		
				{response.sendRedirect("menu1.jsp?login=entrou");}
				//out.println("entrei no 2 <br>");
			}
			

		}

	}else{
		
		{response.sendRedirect("errro.jsp?entra=falhou");}
		//out.println("entrei no 3 <br>");

	}
	
	
}else{
	
	{response.sendRedirect("login.jsp?login=falhou");}
	//out.println("entrei no 4 <br>");

}

stm2.close();   
Con2.close();   
       

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
