/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2013-03-17 19:01:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.*;
import java.sql.*;
import org.apache.jasper.tagplugins.jstl.core.Catch;

public final class menu1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(11);
    _jspx_dependants.put("/sessao1.jsp", Long.valueOf(1362944913578L));
    _jspx_dependants.put("/website.jsp", Long.valueOf(1361887083868L));
    _jspx_dependants.put("/caixa.jsp", Long.valueOf(1361887084026L));
    _jspx_dependants.put("/cobranca.jsp", Long.valueOf(1361887083605L));
    _jspx_dependants.put("/juridico.jsp", Long.valueOf(1361887084006L));
    _jspx_dependants.put("/relatorio.jsp", Long.valueOf(1361887083678L));
    _jspx_dependants.put("/help.jsp", Long.valueOf(1361887084141L));
    _jspx_dependants.put("/operador.jsp", Long.valueOf(1363375937713L));
    _jspx_dependants.put("/config.jsp", Long.valueOf(1362954014485L));
    _jspx_dependants.put("/cadastro.jsp", Long.valueOf(1361978811509L));
    _jspx_dependants.put("/saude.jsp", Long.valueOf(1361887083671L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

// Titulo do Sistema
String w_titulo   = "Sistema JSP";
String w_versaox  = "Atualizado em 10/03/2013 às 17:12";

// Variaveis Banco de Dados
String driver_pes     = "com.mysql.jdbc.Driver";
String db_dados_pes   = "agenda";
String connection_pes = "jdbc:mysql://localhost:3306/" + db_dados_pes;
String user_pes       = "root";
String password_pes   = "12345";



      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Sistema XP</title>\r\n");
      out.write("<link rel='shortcut icon' href='imagens/favicon.ico'>\r\n");
      out.write("\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"menu.css\"/>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\r\n");
      out.write("background-image: url('imagens/logosys.jpg');\r\n");
      out.write("background-attachment: fixed\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".normal {\r\n");
      out.write("\t\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("}\r\n");
      out.write(".anormal {\r\n");
      out.write("\t\tbackground-color: Lavender;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\"><!--\r\n");
      out.write("\r\n");
      out.write("document.onkeydown = keyCatcher;\r\n");
      out.write("\r\n");
      out.write("function keyCatcher() \r\n");
      out.write("{\r\n");
      out.write("   var e = event.srcElement.tagName;\r\n");
      out.write("\r\n");
      out.write("   if (event.keyCode == 8 && e != \"INPUT\" && e != \"TEXTAREA\") \r\n");
      out.write("   {\r\n");
      out.write("      event.cancelBubble = true;\r\n");
      out.write("      event.returnValue = false;\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");

// Rotinas Principais

// config.jsp
// login.jsp
// logar.jsp
// menu1.jsp


      out.write("\r\n");
      out.write("\r\n");

// Declaracao de Variaveis Usadas no JSP
String situa_1 = "";
String w_nome3 = "";
String w_opcao = "";
String sol_1   = "";
String sql1    = "";
String sql2    = "";
String sql3    = "";
String sql4    = "";
String sql5    = "";
String w_tabela = "SISTEMAXP"; // Tabela Banco

String tabelap = "";
String per1    = "";
String per2    = "";
String per3    = "";
String per4    = "";


      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');


//Resgata informacao gravada na sessao
String Minha_sessao1 = (String) session.getAttribute("minha_sessao1");
if (Minha_sessao1 != "" || Minha_sessao1 != null){
	w_nome3 = Minha_sessao1;
	
}else{
	
	if (Minha_sessao1 == null)
	{	
	   w_opcao = "faz";
	  {response.sendRedirect("login.jsp");}
	  return;
	}  
}
if (w_nome3 == "" || w_nome3 == null){
	   w_opcao = "faz";
	  {response.sendRedirect("login.jsp");}
	  return;
}
if (w_opcao != null || w_opcao != ""){
	w_opcao = "";
	

	//Saldação ao usuario
	
	int w_Hora = Integer.parseInt((new java.text.SimpleDateFormat("HH")).format(new java.util.Date()));
	
	String w_AMPM = new java.text.SimpleDateFormat("a").format(new java.util.Date());
	
	if (w_Hora <= 0) {
	    situa_1 = "Boa Madrugada";
	    sol_1   = "imagens/noite.png";
	}
	if (w_Hora > 0 && w_Hora <= 6) {
	    situa_1 = "Boa Madrugada";
	    sol_1   = "imagens/noite.png";
	}
	if (w_Hora > 6 && w_Hora <= 12) {
	    situa_1 = "Bom Dia";
	    sol_1   = "imagens/dia.png";
	}
	if (w_Hora > 12 && w_Hora <= 18) {
	    situa_1 = "Boa Tarde";
	    sol_1   = "imagens/dia.png";
	}
	if (w_Hora >= 19 && w_Hora <= 23) {
	    situa_1 = "Boa Noite";
	    sol_1   = "imagens/noite.png";
	}
	
	
	String w_bomdia = situa_1 + " Seja Bem Vindo, " + w_nome3 + " hoje e, " + new java.text.SimpleDateFormat("EEEE dd 'de' MMMM 'de' yyyy").format(new java.util.Date()) + "<br />";
	
	String w_login        = request.getParameter("login");

	
	//Variaveis de Sessao
	
	String campo1a  = "";
	String campo2a  = "";
	String campo3a  = "";
	String campo4a  = "";
	String campo5a  = "";
	String campo6a  = "";

	// Prepara a Conexao com o Banco
	Class.forName(driver_pes);
	Connection Con = DriverManager.getConnection(connection_pes, user_pes, password_pes);
	Statement stm = Con.createStatement();

	// Busca Usuario
	sql1 = "SELECT * FROM tt_ser_01 WHERE login = '" + w_nome3 + "'";
	ResultSet res1 = stm.executeQuery(sql1);
	while(res1.next()){
		campo1a  = res1.getString("id");
		campo2a  = res1.getString("codigo");
		campo3a  = res1.getString("login");
		campo4a  = "SISTEMAXP,"+res1.getString("programas");
		campo5a  = res1.getString("tipo");
		campo6a  = res1.getString("semana");
	}
    // Fim Busca Usuario

	
	// Fim Verificar dia da Semana e Permissao da Tela 
    
	//out.println(campo1a + "<br>");
	//out.println(campo2a + "<br>");
	//out.println(campo3a + "<br>");
	//out.println(campo4a + "<br>");
	//out.println(campo5a + "<br>");
	//out.println(campo6a + "<br><br>");

	// Busca Permissao
	sql2 = "SELECT * FROM permissoes WHERE login = '" + campo3a + "' AND tabela = '" + w_tabela + "'";
	ResultSet res2 = stm.executeQuery(sql2);
	while(res2.next()){
		tabelap = res2.getString("tabela");
		per1    = res2.getString("incluir");
		per2    = res2.getString("alterar");
		per3    = res2.getString("excluir");
		per4    = res2.getString("imprimir");
	}
	// Fim Busca Permissao

	//out.println(tabelap + "<br>");
	//out.println(per1 + "<br>");
	//out.println(per2 + "<br>");
	//out.println(per3 + "<br>");
	//out.println(per4 + "<br>");

	

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<body  style=\" margin-left: 0px;  margin-top: 0px;  margin-right: 0px;  margin-bottom: 0px; \" onkeydown=\"javascript:if (event.KeyCode==13) event.KeyCode=9; javascript:document.onkeydown = keyCatcher();\" onload=\"document.form1.nome_log.focus();\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div align=\"left\">  <table width=\"200\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\r\n");
      out.write("\t    <tr>\r\n");
      out.write("        <td>\r\n");
      out.write("\r\n");
      out.write("\t    <div align=\"center\">\r\n");
      out.write("            <table width=\"133\" border=\"0\">\r\n");
      out.write("        \r\n");
      out.write("\t\t\t\t<div style=\"Z-INDEX: 600; LEFT: 00px; WIDTH: 616px; POSITION: absolute; TOP: 0px; HEIGHT: 19px\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<IFRAME src=\"user.jsp\" width=\"130\" height=\"22\" scrolling=\"no\" frameborder=\"0\" align=\"left\"></IFRAME>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("        \r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        </td>\r\n");
      out.write("        <td width=\"876\"><div align=\"center\">\r\n");
      out.write("\r\n");
      out.write("        ");
 out.println("<img src='" + sol_1 + "' width=20  height=17  border=0  />"); 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <font face=\"Verdana\" size=\"2\"><b><i>");
 out.println(w_bomdia); 
      out.write("</i></b></font></div></td>\r\n");
      out.write("        <td width=\"7\">&nbsp;</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td><div align=\"center\"><img src=\"imagens/carta.gif\" width=\"40\" height=\"31\"></div></td>\r\n");
      out.write("\t      <td><table width=\"200\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t        <tr>\r\n");
      out.write("\t        \r\n");
      out.write("\r\n");
      out.write("<td align=\"left\"><div id=\"menu\"><ul> \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <li id=\"menu2a\"><h2 align=\"center\"><b>Cadastros</b></h2>\r\n");
      out.write("    <ul id=\"menu3\"> <!-- Inicio Sub-menu -->\r\n");
      out.write("      <li><a href=\"#\" title=\"\" >Cadastro de Adms/Contabilidade\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Incluir</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Consultar</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Cadastro de Associados\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Incluir</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Consultar</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Cadastro de Categoria</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Cadastro de Empresas\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Incluir</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Consultar</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Cadastro de Associados\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Incluir</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Consultar</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Cadastro de Cursos\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Incluir</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Consultar</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Cadastro Carta de Oposição\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Incluir</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Consultar</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Cadastro de Vagas\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Incluir</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Consultar</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Cadastro Etiquetas Federação\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Incluir</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Consultar</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Listagem Socios Grupo de Rua\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Incluir</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Consultar</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Bairros Grupo de Rua\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Incluir</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Consultar</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Consulta CNPJ para Cadastro</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Atendimento ao Socio\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Incluir</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Consultar</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Lista Empregados Sindical\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Incluir</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Consultar</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Cadastro de Aposentado\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Incluir</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Consultar</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Cadastro Clube Tiete\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Incluir</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Consultar</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"index.html\" title=\"\">Trocar Usuario</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"login.jsp\" title=\"\">Sair</a>\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("    </ul> <!-- Fim Sub-menu -->\r\n");
      out.write("  </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</ul></div></td>\r\n");
      out.write("<!-- Fim menu -->\r\n");
      out.write("\r\n");
      out.write("<!-- Inicio menu -->\r\n");
      out.write("<td align=\"left\"><div id=\"menu\"><ul> \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <li id=\"menu2b\"><h2 align=\"center\"><b>Contribuição</b></h2>\r\n");
      out.write("    <ul id=\"menu3\"> <!-- Inicio Sub-menu -->\r\n");
      out.write("      <li><a href=\"#\" title=\"\" >Instrução de Cobrança</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Emissão de Contribuição</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Baixa Manual Mensalidades</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Manutenção Contribuições</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Gerador de Boletos Socios</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Relatório Contribuições Pagas</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Relatório Contribuições em Aberto</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Tratar Arquivo Retorno (Banco)</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Testar Codigo de Barras</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Enviar Guias por E-Mail</a>\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("    </ul> <!-- Fim Sub-menu -->\r\n");
      out.write("  </li>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</ul></div></td>\r\n");
      out.write("<!-- Fim menu -->\r\n");
      out.write("\r\n");
      out.write("<!-- Inicio menu -->\r\n");
      out.write("<td align=\"left\"><div id=\"menu\"><ul> \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <li id=\"menu2c\"><h2 align=\"center\"><b>Relatórios</b></h2>\r\n");
      out.write("    <ul id=\"menu3c\"> <!-- Inicio Sub-menu -->\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Relatório de Empreasas</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Relatório de Associados</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Listagem de Adms/Contabilidade</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Relação de Empregados</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Impressão de Etiquetas\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Empresas</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Contabilidades</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Socios</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Oposição</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Relatório de Baixa Sindical</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Relatório de Baixa Conf./Assist.</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Relatório de Baixas Mensalidades</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Relatório de Carta de Oposição</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Relatório de E-Mails Enviados no Ano</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Relatório de Movimento Caixa</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Relatório Socio do Dia</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Relatório Carne Emitidos Socios</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Emissão de Cracha\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Incluir</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Consultar</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("    </ul> <!-- Fim Sub-menu -->\r\n");
      out.write("  </li>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</ul></div></td>\r\n");
      out.write("<!-- Fim menu -->\r\n");
      out.write("\r\n");
      out.write("<!-- Inicio menu -->\r\n");
      out.write("<td align=\"left\"><div id=\"menu\"><ul> \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <li id=\"menu2d\"><h2 align=\"center\"><b>Sáude</b></h2>\r\n");
      out.write("    <ul id=\"menu3\"> <!-- Inicio Sub-menu -->\r\n");
      out.write("      <li><a href=\"#\" title=\"\" >Atendimento Odontologico</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Cadastro de Médicos/Dentistas\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Incluir</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Consultar</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Agendamento Médico/Odontologico</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Cadastro de Estq. Medicamentos</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Relatório de Estat. Mensal</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Estatistica de Uso dos Serviços Odontologico</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Estatistica de Uso dos Serviços Medicos</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Atendimento Medico</a>\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("    </ul> <!-- Fim Sub-menu -->\r\n");
      out.write("  </li>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</ul></div></td>\r\n");
      out.write("<!-- Fim menu -->\r\n");
      out.write("\r\n");
      out.write("<!-- Inicio menu -->\r\n");
      out.write("<td align=\"left\"><div id=\"menu\"><ul> \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <li id=\"menu2e\"><h2 align=\"center\"><b>Caixa</b></h2>\r\n");
      out.write("    <ul id=\"menu3e\"> <!-- Inicio Sub-menu -->\r\n");
      out.write("      <li><a href=\"#\" title=\"\" >Cadastro de Codigos Caixa</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Cadastro de Caixa</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Relatório de Caixa\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Relatório Mensal</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Relatório Anual</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Relatório do Dia</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Recebimentos Caixa</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Receita</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Cadastro de Cheques</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Relatório de Cheques</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Cadastro de Despesas</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Relatório de Despesas</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Planilha de caixa</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Listagem de Planilha de Caixa\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Relatório Geral</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Relatório de Credito</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Relatório de Debito</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Cadastro de Historico</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Cadastro de Depositos</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Relatório de Depositos</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Recebimentos Diários</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Impressão de DARF</a>\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("    </ul> <!-- Fim Sub-menu -->\r\n");
      out.write("  </li>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</ul></div></td>\r\n");
      out.write("<!-- Fim menu -->\r\n");
      out.write("\r\n");
      out.write("<!-- Inicio menu -->\r\n");
      out.write("<td align=\"left\"><div id=\"menu\"><ul> \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <li id=\"menu2f\"><h2 align=\"center\"><b>Juridico</b></h2>\r\n");
      out.write("    <ul id=\"menu3\"> <!-- Inicio Sub-menu -->\r\n");
      out.write("      <li><a href=\"#\" title=\"\" >Cadastro de Advogados(as)\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Incluir</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Consultar</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Cadastro de Acompanhamento\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Incluir</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Consultar</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Protocolo de Assembleias</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Cadastro de Pisos</a>\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("    </ul> <!-- Fim Sub-menu -->\r\n");
      out.write("  </li>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</ul></div></td>\r\n");
      out.write("<!-- Fim menu -->\r\n");
      out.write("\r\n");
      out.write("<!-- Inicio menu -->\r\n");
      out.write("<td align=\"left\"><div id=\"menu\"><ul> \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <li id=\"menu2g\"><h2 align=\"center\"><b>Web Site</b></h2>\r\n");
      out.write("    <ul id=\"menu3g\"> <!-- Inicio Sub-menu -->\r\n");
      out.write("      <li><a href=\"#\" title=\"\" >Palavra do Presidente</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Noticias de Ultima Hora</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Coluna Principal</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Fique por Dentro da Noticia</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">O Contato</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Destaques</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Destaques 2</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Fotos do Site</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Informativo</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Pisos Salariais</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Links\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul> \r\n");
      out.write("          <li><a href=\"#\" title=\"\">Juridico</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Saude</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Odontologico</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Servicos</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Cursos</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Lazer</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Subsedes</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Filie-se ao Sindicato</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Noticias\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Incluir</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Consultar</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("    </ul> <!-- Fim Sub-menu -->\r\n");
      out.write("  </li>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</ul></div></td>\r\n");
      out.write("<!-- Fim menu -->\r\n");
      out.write("\r\n");
      out.write("<!-- Inicio menu -->\r\n");
      out.write("<td align=\"left\"><div id=\"menu\"><ul> \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <li id=\"menu2h\"><h2 align=\"center\"><b>Operador</b></h2>\r\n");
      out.write("    <ul id=\"menu3h\"> <!-- Inicio Sub-menu -->\r\n");
      out.write("      <li><a href=\"infor.jsp\" title=\"\" >Informações do Sistema</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Configurar Impressão</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Configurar Servidor de Dados</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Configurações do Sistemar</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"cad_senha.jsp\" title=\"\">Cadastro de Senhas\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Incluir</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Consultar</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"send.jsp\" title=\"\">Enviar Mensagem(send)</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Sistema Modelo</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Calculadora</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Reindex (Organizar)</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Backup da Base de Dados</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Cancelamento Caixa</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Abrir Receita Caixa</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Cronometro</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Alterar Foto do Socio</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Alterar Foto Clube</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Testar Desempenho da Rede</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Bate Papo (Chat)</a>\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("    </ul> <!-- Fim Sub-menu -->\r\n");
      out.write("  </li>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</ul></div></td>\r\n");
      out.write("<!-- Fim menu -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Inicio menu -->\r\n");
      out.write("<td align=\"left\"><div id=\"menu\"><ul> \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <li id=\"menu2hx\"><h2 align=\"center\"><b>Help</b></h2>\r\n");
      out.write("    <ul id=\"menu3hx\"> <!-- Inicio Sub-menu -->\r\n");
      out.write("      <li><a href=\"#\" title=\"\" >Informações do Sistema</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Configurar Impressão</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Configurar Servidor de Dados</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Configurações do Sistemar</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Cadastro de Senhas\r\n");
      out.write("\t  <img src=\"imagens/arrows.gif\" width=\"8\" height=\"8\" border=\"0\"/></a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Incluir</a></li>\r\n");
      out.write("          <li><a href=\"#\" title=\"\">Consultar</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Enviar Mensagem(send)</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Sistema Modelo</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Calculadora</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Reindex (Organizar)</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Backup da Base de Dados</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Cancelamento Caixa</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Abrir Receita Caixa</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Cronometro</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Alterar Foto do Socio</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Alterar Foto Clube</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Testar Desempenho da Rede</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" title=\"\">Bate Papo (Chat)</a>\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("    </ul> <!-- Fim Sub-menu -->\r\n");
      out.write("  </li>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</ul></div></td>\r\n");
      out.write("<!-- Fim menu -->\r\n");
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("<td><img src=\"imagens/px1.gif\" width=\"3\" height=\"10\"></td>\r\n");
      out.write("\t          \r\n");
      out.write("\t        </tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t      </table></td>\r\n");
      out.write("\t            <td>&nbsp;</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td>&nbsp;</td>\r\n");
      out.write("        <td align=\"left\" valign=\"top\"><font color=\"#000000\" size=\"1\">");
 out.println(w_versaox); 
      out.write("</font></strong> </td>\r\n");
      out.write("        <td>&nbsp;</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("\r\n");
      out.write("\t  </table>\r\n");
      out.write("\t  <br/>\r\n");
      out.write("\t  <br/>\r\n");
      out.write("\t  <br/>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <div align=center>\r\n");
      out.write("\t  \r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script> window.focus();</script>\r\n");
      out.write("\t</body>\r\n");
      out.write("\t\r\n");
      out.write("\t<script> window.focus();</script>\r\n");
      out.write("\t<script type=\"text/javascrip\">document.form1.nome_log.focus(); </script>\r\n");

}

      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
