/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2013-03-09 08:22:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;

public final class paginacao_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/config.jsp", Long.valueOf(1361887084132L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head><title>Aprendendo JSP</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");

// Titulo do Sistema
String w_titulo = "Sistema JSP";

// Variaveis Banco de Dados
String driver_pes     = "com.mysql.jdbc.Driver";
String db_dados_pes   = "agenda";
String connection_pes = "jdbc:mysql://localhost:3306/" + db_dados_pes;
String user_pes       = "root";
String password_pes   = "12345";



      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Sistema XP</title>\r\n");
      out.write("<link rel='shortcut icon' href='imagens/favicon.ico'>\r\n");
      out.write("\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"menu.css\"/>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\r\n");
      out.write("background-image: url('imagens/logosys.jpg');\r\n");
      out.write("background-attachment: fixed\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".normal {\r\n");
      out.write("\t\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("}\r\n");
      out.write(".anormal {\r\n");
      out.write("\t\tbackground-color: Lavender;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\"><!--\r\n");
      out.write("\r\n");
      out.write("document.onkeydown = keyCatcher;\r\n");
      out.write("\r\n");
      out.write("function keyCatcher() \r\n");
      out.write("{\r\n");
      out.write("   var e = event.srcElement.tagName;\r\n");
      out.write("\r\n");
      out.write("   if (event.keyCode == 8 && e != \"INPUT\" && e != \"TEXTAREA\") \r\n");
      out.write("   {\r\n");
      out.write("      event.cancelBubble = true;\r\n");
      out.write("      event.returnValue = false;\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");

// Rotinas Principais

// config.jsp
// login.jsp
// logar.jsp
// menu1.jsp


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


//Declaracao de Variaveis Usadas no JSP
String situa_1 = "";
String vr1 = request.getParameter("opcao");
String ww_mensage = "";
int id_s            = 0;
String w_tabela = "ADMS"; // Tabela Banco
String w_nome3 = "";
String w_opcao = "";
String sol_1   = "";
String sql1    = "";
String sql2    = "";
String sql3    = "";
String sql4    = "";
String sql5    = "";

String tabelap = "";
String per1    = "";
String per2    = "";
String per3    = "";
String per4    = "";

String campo1  = "";
String campo2  = "";
String campo3  = "";
String campo4  = "";
String campo5  = "";
String campo6  = "";
String campo7  = "";
String campo8  = "";
String campo9  = "";
String campo10 = "";
String campo11 = "";
String campo12 = "";
String campo13 = "";
String campo14 = "";
String campo15 = "";

String bus_cod    = request.getParameter("Cod_2");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

  // ********************
  // Este exemplo mostra como paginar os resultados de uma
  // tabela MySQL
  // o nome da base de dados é "test"
 
  
  // conn é a conexão com o banco de dados
  int limit = 3; // quantidade de resultados por página                

  String driver     = "com.mysql.jdbc.Driver";
  String db_dados   = "agenda";
  String connection = "jdbc:mysql://localhost:3306/" + db_dados;
  String user       = "root";
  String password   = "12345";
  Class.forName(driver);
  Connection Con = DriverManager.getConnection(connection, user, password);

  // obtém a quantidade de registros
  PreparedStatement pstmt = Con.prepareStatement(
		"SELECT COUNT(*) AS c FROM permissoes");
  ResultSet rs = pstmt.executeQuery();
  rs.next();
  int total_rows = Integer.parseInt(rs.getString("c"));
  

  String pagina = request.getParameter("pagina"); // página atual
  if(pagina == null){
    pagina = "1";
  }
  
  int limitValue = (Integer.parseInt(pagina) * limit) - limit;  
  
  PreparedStatement pstmt2 = Con.prepareStatement(
		"SELECT * FROM permissoes ORDER BY login ASC LIMIT " + limitValue + ", " + limit);
  ResultSet rs2 = pstmt2.executeQuery();

  
      out.write("\r\n");
      out.write("  <div align=\"center\">\r\n");
      out.write("  \t\t<table width=\"200\" border=\"16\" bgcolor=\"#FFFFFF\" bordercolor=\"#5A9CB1\">\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td><table width=\"200\" border=\"1\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td><b><font size=\"3\" face=\"Verdana\">Login</font></b></td>\r\n");
      out.write("          <td><b><font size=\"3\" face=\"Verdana\">Tabela</font></b></td>\r\n");
      out.write("          <td><b><font size=\"3\" face=\"Verdana\">Incluir</font></b></td>\r\n");
      out.write("          <td><b><font size=\"3\" face=\"Verdana\">Alterar</font></b></td>\r\n");
      out.write("          <td><b><font size=\"3\" face=\"Verdana\">Excluir</font></b></td>\r\n");
      out.write("          <td><b><font size=\"3\" face=\"Verdana\">Imprimir</font></b></td>\r\n");
      out.write("          <td></td>\r\n");
      out.write("          <td></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  ");

  
  while(rs2.next()) {
	  
	  int    id2    = rs2.getInt("id");
	  String Edit1  = rs2.getString("login");
	  String Edit2  = rs2.getString("tabela");
	  String Edit3  = rs2.getString("incluir");
	  String Edit4  = rs2.getString("alterar");
	  String Edit5  = rs2.getString("excluir");
	  String Edit6  = rs2.getString("imprimir");
    

      out.write("\r\n");
      out.write("\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td>");
 out.println(Edit1); 
      out.write("</td>\r\n");
      out.write("        <td>\r\n");
        
			//ResultSet rslist;
			
			rs2 = pstmt.executeQuery("SHOW TABLES");
			    
			
      out.write("\r\n");
      out.write("\t\t\t    <select type=\"text\" id=\"Edit2\" name=\"Edit2\" value=\"");
 out.println(Edit2); 
      out.write(" \" />\r\n");
      out.write("\t\t\t");
    
			while ( rs2.next() ) {  
			    String lastName = rs2.getString(1);
			    
			
      out.write("\r\n");
      out.write("\t\t\t    <option value=\"");
 out.println(lastName); 
      out.write('"');
      out.write('>');
      out.write(' ');
 out.println(lastName); 
      out.write(" </option>\r\n");
      out.write("\t\t\t");

			}  
			
      out.write("\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    </select>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("        \r\n");
      out.write("                <select type=\"text\"    name=\"Edit3\"  value=\"");
 out.println(Edit3); 
      out.write("\" style=\" font-family: Verdana; font-size: 14px; \">\r\n");
      out.write("        ");

		if (Edit3 != null || Edit3 != "")
		{
		
      out.write("\t\r\n");
      out.write("\t     \t<option value=\"");
 out.println(Edit3); 
      out.write('"');
      out.write('>');
      out.write(' ');
 out.println(Edit3); 
      out.write(" </option>\r\n");
      out.write("\t        <option value=\"SIM\"> SIM </option>\r\n");
      out.write("\t        <option value=\"NAO\"> NAO </option>\r\n");
      out.write("\t\t");
	
		}else{
		
      out.write("\t\r\n");
      out.write("\t     \t<option value=\"\">  </option>\r\n");
      out.write("\t        <option value=\"SIM\"> SIM </option>\r\n");
      out.write("\t        <option value=\"NAO\"> NAO </option>\r\n");
      out.write("\t\t");
            
		}
	    
      out.write("\r\n");
      out.write("        </select>\r\n");
      out.write("        \r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("        \r\n");
      out.write("                <select type=\"text\"    name=\"Edit4\"  value=\"");
 out.println(Edit4); 
      out.write("\" style=\" font-family: Verdana; font-size: 14px; \">\r\n");
      out.write("        ");

		if (Edit4 != null || Edit4 != "")
		{
		
      out.write("\t\r\n");
      out.write("\t     \t<option value=\"");
 out.println(Edit4); 
      out.write('"');
      out.write('>');
      out.write(' ');
 out.println(Edit4); 
      out.write(" </option>\r\n");
      out.write("\t        <option value=\"SIM\"> SIM </option>\r\n");
      out.write("\t        <option value=\"NAO\"> NAO </option>\r\n");
      out.write("\t\t");
	
		}else{
		
      out.write("\t\r\n");
      out.write("\t     \t<option value=\"\">  </option>\r\n");
      out.write("\t        <option value=\"SIM\"> SIM </option>\r\n");
      out.write("\t        <option value=\"NAO\"> NAO </option>\r\n");
      out.write("\t\t");
            
		}
	    
      out.write("\r\n");
      out.write("        </select>\r\n");
      out.write("        \r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("        \r\n");
      out.write("        <select type=\"text\"    name=\"Edit5\"  value=\"");
 out.println(Edit5); 
      out.write("\" style=\" font-family: Verdana; font-size: 14px; \">\r\n");
      out.write("        ");

		if (Edit5 != null || Edit5 != "")
		{
		
      out.write("\t\r\n");
      out.write("\t     \t<option value=\"");
 out.println(Edit5); 
      out.write('"');
      out.write('>');
      out.write(' ');
 out.println(Edit5); 
      out.write(" </option>\r\n");
      out.write("\t        <option value=\"SIM\"> SIM </option>\r\n");
      out.write("\t        <option value=\"NAO\"> NAO </option>\r\n");
      out.write("\t\t");
	
		}else{
		
      out.write("\t\r\n");
      out.write("\t     \t<option value=\"\">  </option>\r\n");
      out.write("\t        <option value=\"SIM\"> SIM </option>\r\n");
      out.write("\t        <option value=\"NAO\"> NAO </option>\r\n");
      out.write("\t\t");
            
		}
	    
      out.write("\r\n");
      out.write("        </select>\r\n");
      out.write("        \r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("        <select type=\"text\"    name=\"Edit6\"  value=\"");
 out.println(Edit6); 
      out.write("\" style=\" font-family: Verdana; font-size: 14px; \">\r\n");
      out.write("        ");

		if (Edit6 != null || Edit6 != "")
		{
		
      out.write("\t\r\n");
      out.write("\t     \t<option value=\"");
 out.println(Edit6); 
      out.write('"');
      out.write('>');
      out.write(' ');
 out.println(Edit6); 
      out.write(" </option>\r\n");
      out.write("\t        <option value=\"SIM\"> SIM </option>\r\n");
      out.write("\t        <option value=\"NAO\"> NAO </option>\r\n");
      out.write("\t\t");
	
		}else{
		
      out.write("\t\r\n");
      out.write("\t     \t<option value=\"\">  </option>\r\n");
      out.write("\t        <option value=\"SIM\"> SIM </option>\r\n");
      out.write("\t        <option value=\"NAO\"> NAO </option>\r\n");
      out.write("\t\t");
            
		}
	    
      out.write("\r\n");
      out.write("        </select>\r\n");
      out.write("        \r\n");
      out.write("        </td>\r\n");
      out.write("        <td><img src=\"imagens/editar.gif\"></td>\r\n");
      out.write("        <td><img src=\"imagens/excluir.gif\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("\r\n");

}

      out.write("\t\r\n");
      out.write("\r\n");
      out.write("  </table></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("  <td><img src=\"imagens/novo.gif\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- Fim do Form -->\r\n");
      out.write("      </td>\r\n");
      out.write("      <td>&nbsp;</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("\r\n");
      out.write("\t  </table>\r\n");
      out.write("\t  <br/>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <div align=center>\r\n");
      out.write("\t  \r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("<div align=\"center\">  \r\n");
  
  
  int anterior;
  if(Integer.parseInt(pagina) != 1){  
    anterior = Integer.parseInt(pagina) - 1; 
    out.println("<a href=?pagina=" + anterior + "> Anteriores</a>");
  }
  else{ 
    out.println(limit + " Anteriores ");
  }  
  int numOfPages = total_rows / limit;  
  int i;
  int p = 0;
  
  for(i = 1; i <= numOfPages; i++){
      
    	if(i == Integer.parseInt(pagina)){ 
    	      out.println("<b>" + i + "</b> "); 
    	      
    	    }
    	    else{
    	    	
    	    	if (i <= 10 ){
    	            out.println("<a href=?pagina=" + i + ">" + i + "</a> ");
    	            if (p == 10){
    	            	p = 0;	
    	            }
    	            
    	        }

    	    }
    	    	    
    	        
  }
  
  if((total_rows % limit) != 0){ 
    if(i == Integer.parseInt(pagina)){ 
      out.println(i + " "); 
    }
    else{ 
     	
      out.println("<a href=?pagina=" + i + ">" + i + "</a> "); 
    } 
  } 

  
  int proxima;
  if((total_rows - (limit * Integer.parseInt(pagina))) > 0){ 
    proxima = Integer.parseInt(pagina) + 1; 
          
    out.println("...<a href=?pagina=" + proxima + ">Próximos </a>");  
  }
  else {
    out.println("Próximos " + limit);
  }

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
