/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2013-03-17 23:08:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.sql.*;
import java.util.*;
import java.text.*;
import java.sql.*;
import org.apache.jasper.tagplugins.jstl.core.Catch;

public final class send_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/sessao1.jsp", Long.valueOf(1362944913578L));
    _jspx_dependants.put("/config.jsp", Long.valueOf(1362954014485L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("\r\n");
      out.write("//document.onkeydown = keyCatcher;\r\n");
      out.write("\r\n");
      out.write("function keyCatcher() \r\n");
      out.write("{\r\n");
      out.write("   var e = event.srcElement.tagName;\r\n");
      out.write("\r\n");
      out.write("   if (event.keyCode == 8 && e != \"INPUT\" && e != \"TEXTAREA\") \r\n");
      out.write("   {\r\n");
      out.write("      event.cancelBubble = true;\r\n");
      out.write("      event.returnValue = false;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   if (event.keyCode == 27) \r\n");
      out.write("   {\r\n");
      out.write("\t\twindow.location=\"\";\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("window.focus();\r\n");
      out.write("document.form1.nome_log.focus();\r\n");
      out.write("\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".normal {\r\n");
      out.write("\t\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("}\r\n");
      out.write(".anormal {\r\n");
      out.write("\t\tbackground-color: Lavender;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

// Titulo do Sistema
String w_titulo   = "Sistema JSP";
String w_versaox  = "Atualizado em 10/03/2013 às 17:12";

// Variaveis Banco de Dados
String driver_pes     = "com.mysql.jdbc.Driver";
String db_dados_pes   = "agenda";
String connection_pes = "jdbc:mysql://localhost:3306/" + db_dados_pes;
String user_pes       = "root";
String password_pes   = "12345";



      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Sistema XP</title>\r\n");
      out.write("<link rel='shortcut icon' href='imagens/favicon.ico'>\r\n");
      out.write("\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"menu.css\"/>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\r\n");
      out.write("background-image: url('imagens/logosys.jpg');\r\n");
      out.write("background-attachment: fixed\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".normal {\r\n");
      out.write("\t\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("}\r\n");
      out.write(".anormal {\r\n");
      out.write("\t\tbackground-color: Lavender;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\"><!--\r\n");
      out.write("\r\n");
      out.write("document.onkeydown = keyCatcher;\r\n");
      out.write("\r\n");
      out.write("function keyCatcher() \r\n");
      out.write("{\r\n");
      out.write("   var e = event.srcElement.tagName;\r\n");
      out.write("\r\n");
      out.write("   if (event.keyCode == 8 && e != \"INPUT\" && e != \"TEXTAREA\") \r\n");
      out.write("   {\r\n");
      out.write("      event.cancelBubble = true;\r\n");
      out.write("      event.returnValue = false;\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");

// Rotinas Principais

// config.jsp
// login.jsp
// logar.jsp
// menu1.jsp


      out.write("\r\n");
      out.write("\r\n");


//Declaracao de Variaveis Usadas no JSP
String situa_1 = "";
String vr1 = request.getParameter("opcao");
String ww_mensage = "";
int id_s            = 0;
String w_tabela   = "TT_SER_01"; // Tabela Banco
String w_programa = "SEND"; // Tela
String w_nome3 = "";
String w_opcao = "";
String sol_1   = "";
String sql1    = "";
String sql2    = "";
String sql3    = "";
String sql4    = "";
String sql5    = "";

String tabelap = "";
String per1    = "";
String per2    = "";
String per3    = "";
String per4    = "";

String campo1  = "";
String campo2  = "";
String campo3  = "";
String campo4  = "";
String campo5  = "";
String campo6  = "";
String campo7  = "";
String campo8  = "";
String campo9  = "";
String campo10 = "";
String campo11 = "";
String campo12 = "";
String campo13 = "";
String campo14 = "";
String campo15 = "";

String bus_cod    = request.getParameter("Cod_2");

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');


//Resgata informacao gravada na sessao
String Minha_sessao1 = (String) session.getAttribute("minha_sessao1");
if (Minha_sessao1 != "" || Minha_sessao1 != null){
	w_nome3 = Minha_sessao1;
	
}else{
	
	if (Minha_sessao1 == null)
	{	
	   w_opcao = "faz";
	  {response.sendRedirect("login.jsp");}
	  return;
	}  
}
if (w_nome3 == "" || w_nome3 == null){
	   w_opcao = "faz";
	  {response.sendRedirect("login.jsp");}
	  return;
}
if (w_opcao != null || w_opcao != ""){
	w_opcao = "";
	

	//Saldação ao usuario
	
	int w_Hora = Integer.parseInt((new java.text.SimpleDateFormat("HH")).format(new java.util.Date()));
	
	String w_AMPM = new java.text.SimpleDateFormat("a").format(new java.util.Date());
	
	if (w_Hora <= 0) {
	    situa_1 = "Boa Madrugada";
	    sol_1   = "imagens/noite.png";
	}
	if (w_Hora > 0 && w_Hora <= 6) {
	    situa_1 = "Boa Madrugada";
	    sol_1   = "imagens/noite.png";
	}
	if (w_Hora > 6 && w_Hora <= 12) {
	    situa_1 = "Bom Dia";
	    sol_1   = "imagens/dia.png";
	}
	if (w_Hora > 12 && w_Hora <= 18) {
	    situa_1 = "Boa Tarde";
	    sol_1   = "imagens/dia.png";
	}
	if (w_Hora >= 19 && w_Hora <= 23) {
	    situa_1 = "Boa Noite";
	    sol_1   = "imagens/noite.png";
	}
	
	
	String w_bomdia = situa_1 + " Seja Bem Vindo, " + w_nome3 + " hoje e, " + new java.text.SimpleDateFormat("EEEE dd 'de' MMMM 'de' yyyy").format(new java.util.Date()) + "<br />";
	
	String w_login        = request.getParameter("login");

	
	//Variaveis de Sessao
	
	String campo1a  = "";
	String campo2a  = "";
	String campo3a  = "";
	String campo4a  = "";
	String campo5a  = "";
	String campo6a  = "";

	// Prepara a Conexao com o Banco
	Class.forName(driver_pes);
	Connection Con = DriverManager.getConnection(connection_pes, user_pes, password_pes);
	Statement stm = Con.createStatement();

	// Busca Usuario
	sql1 = "SELECT * FROM tt_ser_01 WHERE login = '" + w_nome3 + "'";
	ResultSet res1 = stm.executeQuery(sql1);
	while(res1.next()){
		campo1a  = res1.getString("id");
		campo2a  = res1.getString("codigo");
		campo3a  = res1.getString("login");
		campo4a  = "SISTEMAXP,"+res1.getString("programas");
		campo5a  = res1.getString("tipo");
		campo6a  = res1.getString("semana");
	}
    // Fim Busca Usuario

	
	// Fim Verificar dia da Semana e Permissao da Tela 
    
	//out.println(campo1a + "<br>");
	//out.println(campo2a + "<br>");
	//out.println(campo3a + "<br>");
	//out.println(campo4a + "<br>");
	//out.println(campo5a + "<br>");
	//out.println(campo6a + "<br><br>");

	// Busca Permissao
	sql2 = "SELECT * FROM permissoes WHERE login = '" + campo3a + "' AND tabela = '" + w_tabela + "'";
	ResultSet res2 = stm.executeQuery(sql2);
	while(res2.next()){
		tabelap = res2.getString("tabela");
		per1    = res2.getString("incluir");
		per2    = res2.getString("alterar");
		per3    = res2.getString("excluir");
		per4    = res2.getString("imprimir");
	}
	// Fim Busca Permissao

	//out.println(tabelap + "<br>");
	//out.println(per1 + "<br>");
	//out.println(per2 + "<br>");
	//out.println(per3 + "<br>");
	//out.println(per4 + "<br>");

	

      out.write("\r\n");
      out.write("\r\n");


//Rotina Verifica Permissao da Tela 

String p_PROGM = w_programa;
String strT = campo4a;
String[] f = strT.split(",");
int fazP = 0;

for (int i= 0; i<=f.length-1; i++){	
		if (p_PROGM.toUpperCase().equals(f[i])){
			fazP = 3;
		}
}

if (fazP != 3){
	
	{response.sendRedirect("enaaurlnp.jsp");}
	
}



      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<body  style=\" margin-left: 0px;  margin-top: 0px;  margin-right: 0px;  margin-bottom: 0px; \" onkeydown=\"javascript:if (event.KeyCode==13) event.KeyCode=9; javascript:document.onkeydown = keyCatcher();\" onload=\"document.form1.nome_log.focus();\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div align=\"left\">  <table width=\"200\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\r\n");
      out.write("\t    <tr>\r\n");
      out.write("        <td>\r\n");
      out.write("        \r\n");
      out.write("\t    <div align=\"center\">\r\n");
      out.write("            <table width=\"133\" border=\"0\">\r\n");
      out.write("        \r\n");
      out.write("\t\t\t\t<div style=\"Z-INDEX: 600; LEFT: 00px; WIDTH: 616px; POSITION: absolute; TOP: 0px; HEIGHT: 19px\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<IFRAME src=\"user.jsp\" width=\"130\" height=\"22\" scrolling=\"no\" frameborder=\"0\" align=\"left\"></IFRAME>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("        \r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        </td>\r\n");
      out.write("        <td width=\"876\"><div align=\"center\">\r\n");
      out.write("\r\n");
      out.write("        ");
 out.println("<img src='" + sol_1 + "' width=20  height=17  border=0  />"); 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <font face=\"Verdana\" size=\"2\"><b><i>");
 out.println(w_bomdia); 
      out.write("</i></b></font></div></td>\r\n");
      out.write("        <td width=\"7\">&nbsp;</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td><div align=\"center\"><img src=\"imagens/carta.gif\" width=\"40\" height=\"31\"></div></td>\r\n");
      out.write("\t      <td><table width=\"200\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t        <tr>\r\n");
      out.write("\t        \r\n");
      out.write("\t        \r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"3\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/cadastro.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"4\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/contribuicao.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"4\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/relatorios.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"4\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/saude.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"4\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/juridico.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"4\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/caixa.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"4\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/website.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"4\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/operador.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"4\" height=\"30\"></td>\r\n");
      out.write("          <td><img src=\"imagens/help.png\" width=\"95\" height=\"28\"></td>\r\n");
      out.write("          <td><img src=\"imagens/px1.gif\" width=\"3\" height=\"30\"></td>\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("        </tr>\t\t\t\r\n");
      out.write("\t      </table></td>\r\n");
      out.write("\t            <td>&nbsp;</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td>&nbsp;</td>\r\n");
      out.write("        <td align=\"left\" valign=\"top\"><font color=\"#000000\" size=\"1\">");
 out.println(w_versaox); 
      out.write("</font></td>\r\n");
      out.write("        <td>&nbsp;</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td>&nbsp;</td>\r\n");
      out.write("        <td align=\"left\" valign=\"top\">\r\n");
      out.write("        <!--  Inicio do Form -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t <div align=center>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("<table width=\"473\" border=\"16\" bordercolor=\"#5A9CB1\" bgcolor=\"#FFFFFF\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td><div align=\"center\">\r\n");
      out.write("                  <table width=\"99%\" border=\"0\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td width=\"82%\" height=\"42\"><div align=\"left\"><b><font size=\"5\" face=\"Verdana\" color=\"#5A9CB1\"><img src=\"imagens/px1.gif\" width=\"10\" height=\"10\">Enviar Mensagem</font></b></div></td>\r\n");
      out.write("                      <td width=\"18%\"><div align=\"center\"><b><font size=\"2\" face=\"Verdana\">");
 out.println(ww_mensage); 
      out.write("</font></b></div></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("              </div></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td valign=\"top\">                <div align=\"center\">\r\n");
      out.write("\t\t\t\t<form name=\"form1\" method=\"post\" action=\"cad_senha.jsp\">\r\n");
      out.write("\t\t\t\t  <table width=\"75%\" border=\"0\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td><div align=\"center\">\r\n");
      out.write("                        <table width=\"100%\" border=\"0\" cellpadding=\"0\">\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td width=\"23%\"><div align=\"right\"><b><font size=\"2\" face=\"Verdana\">Usuario.:</font></b></div></td>\r\n");
      out.write("                            <td width=\"77%\"><select name=\"campo1\" type=\"text\" id=\"campo1\" style=\" font-family: Verdana; font-size: 14px;  height:23px;width:296px;  \" onfocus=\"this.className='anormal'\"  onblur=\"this.className='normal'\" value=\"\" >\r\n");
      out.write("                            <option value=\"\">  </option>\r\n");
      out.write("                            <option value=\"TODOS\"> TODOS </option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

							// obtém lista de tabelas do banco
							Statement pstmt0 = Con.createStatement(); 
							ResultSet res4;
							        
							res4 = pstmt0.executeQuery("SELECT * FROM useronline");
							
							while ( res4.next() ) {  
									String lastName = res4.getString(6);
										    
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"");
 out.println(lastName.toUpperCase()); 
      out.write('"');
      out.write('>');
      out.write(' ');
 out.println(lastName.toUpperCase()); 
      out.write(" </option>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
    
							}
										
							
      out.write("\r\n");
      out.write("                            \r\n");
      out.write("                            </select>\r\n");
      out.write("                            </td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td><div align=\"right\"><b><font size=\"2\" face=\"Verdana\">Mensagem.:</font></b></div></td>\r\n");
      out.write("                            <td>&nbsp;</td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                        <table width=\"85%\" border=\"0\" cellpadding=\"0\">\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td width=\"19%\" valign=\"top\"><div align=\"center\"><b>\r\n");
      out.write("                            <textarea name=\"campo2\" cols=\"10\" rows=\"10\" id=\"campo2\" style=\" font-family: Verdana; font-size: 14px;  width:400px;  \" onFocus=\"this.className='anormal'\"  onBlur=\"this.className='normal'\" ></textarea>\r\n");
      out.write("</b></div></td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                        </div></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("                  <img src=\"imagens/px1.gif\" width=\"10\" height=\"4\">\r\n");
      out.write("                </form>\r\n");
      out.write("                  <table width=\"417\" border=\"0\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td width=\"15\"><img src=\"imagens/px1.gif\" width=\"15\" height=\"8\"></td>\r\n");
      out.write("                      <td width=\"460\"><div align=\"center\">\r\n");
      out.write("                          <!-- Inicio do Botoes de chamada -->\r\n");
      out.write("                          <table width=\"242\" border=\"0\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                            <td width=\"313\"><div align=\"center\">\r\n");
      out.write("                              <a href=\"#\" ><img src=\"imagens/botaoazul_enviar.PNG\" width=\"92\" height=\"22\" border=\"0\"></a>                              </div></td>          \r\n");
      out.write("                              <td width=\"263\"><div align=\"center\"><a href=\"menu1.jsp\" ><img src=\"imagens/botaoazul25.PNG\" width=\"92\" height=\"22\" border=\"0\"></a></div></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                          </table>\r\n");
      out.write("                          <!--  Fim dos Botoes de chamada -->\r\n");
      out.write("                      </div></td>\r\n");
      out.write("                      <td width=\"27\" valign=\"bottom\"><img src=\"imagens/vacina.JPG\" width=\"27\" height=\"38\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("              </div>            </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Fim do Form -->\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>&nbsp;</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("\r\n");
      out.write("\t  </table>\r\n");
      out.write("\t  <br/>\r\n");
      out.write("\t  <br/>\r\n");
      out.write("\t  <br/>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <div align=center>\r\n");
      out.write("\t  \r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<div align=\"center\">  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</body>\r\n");
      out.write("\t\r\n");
      out.write("</html>\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
