/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2013-03-20 21:35:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.sql.*;
import java.util.*;
import java.text.*;
import java.sql.*;
import java.util.Date;
import java.text.SimpleDateFormat.*;
import org.apache.jasper.tagplugins.jstl.core.Catch;

public final class user_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/sessao1.jsp", Long.valueOf(1362944913578L));
    _jspx_dependants.put("/config.jsp", Long.valueOf(1362954014485L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("\r\n");
      out.write("//document.onkeydown = keyCatcher;\r\n");
      out.write("\r\n");
      out.write("function keyCatcher() \r\n");
      out.write("{\r\n");
      out.write("   var e = event.srcElement.tagName;\r\n");
      out.write("\r\n");
      out.write("   if (event.keyCode == 8 && e != \"INPUT\" && e != \"TEXTAREA\") \r\n");
      out.write("   {\r\n");
      out.write("      event.cancelBubble = true;\r\n");
      out.write("      event.returnValue = false;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   if (event.keyCode == 27) \r\n");
      out.write("   {\r\n");
      out.write("\t\twindow.location=\"\";\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("window.focus();\r\n");
      out.write("document.form1.nome_log.focus();\r\n");
      out.write("\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".normal {\r\n");
      out.write("\t\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("}\r\n");
      out.write(".anormal {\r\n");
      out.write("\t\tbackground-color: Lavender;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

// Titulo do Sistema
String w_titulo   = "Sistema JSP";
String w_versaox  = "Atualizado em 10/03/2013 às 17:12";

// Variaveis Banco de Dados
String driver_pes     = "com.mysql.jdbc.Driver";
String db_dados_pes   = "agenda";
String connection_pes = "jdbc:mysql://localhost:3306/" + db_dados_pes;
String user_pes       = "root";
String password_pes   = "12345";



      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Sistema XP</title>\r\n");
      out.write("<link rel='shortcut icon' href='imagens/favicon.ico'>\r\n");
      out.write("\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"menu.css\"/>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\r\n");
      out.write("background-image: url('imagens/logosys.jpg');\r\n");
      out.write("background-attachment: fixed\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".normal {\r\n");
      out.write("\t\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("}\r\n");
      out.write(".anormal {\r\n");
      out.write("\t\tbackground-color: Lavender;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\"><!--\r\n");
      out.write("\r\n");
      out.write("document.onkeydown = keyCatcher;\r\n");
      out.write("\r\n");
      out.write("function keyCatcher() \r\n");
      out.write("{\r\n");
      out.write("   var e = event.srcElement.tagName;\r\n");
      out.write("\r\n");
      out.write("   if (event.keyCode == 8 && e != \"INPUT\" && e != \"TEXTAREA\") \r\n");
      out.write("   {\r\n");
      out.write("      event.cancelBubble = true;\r\n");
      out.write("      event.returnValue = false;\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");

// Rotinas Principais

// config.jsp
// login.jsp
// logar.jsp
// menu1.jsp


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


//Declaracao de Variaveis Usadas no JSP
String situa_1 = "";
String vr1 = request.getParameter("opcao");
String ww_mensage = "";
int id_s            = 0;
int timestamp = 0;
String w_tabela = "ADMS"; // Tabela Banco
String w_nome3 = "";
String w_opcao = "";
String sol_1   = "";
String sql1    = "";
String sql2    = "";
String sql3    = "";
String sql4    = "";
String sql5    = "";

String tabelap = "";
String per1    = "";
String per2    = "";
String per3    = "";
String per4    = "";

String campo1  = "";
String campo2  = "";
String campo3  = "";
String campo4  = "";
String campo5  = "";
String campo6  = "";
String campo7  = "";
String campo8  = "";
String campo9  = "";
String campo10 = "";
String campo11 = "";
String campo12 = "";
String campo13 = "";
String campo14 = "";
String campo15 = "";
String usuarios2 = "";
String hora_user2 = "";

String bus_cod    = request.getParameter("Cod_2");

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');


//Resgata informacao gravada na sessao
String Minha_sessao1 = (String) session.getAttribute("minha_sessao1");
if (Minha_sessao1 != "" || Minha_sessao1 != null){
	w_nome3 = Minha_sessao1;
	
}else{
	
	if (Minha_sessao1 == null)
	{	
	   w_opcao = "faz";
	  {response.sendRedirect("login.jsp");}
	  return;
	}  
}
if (w_nome3 == "" || w_nome3 == null){
	   w_opcao = "faz";
	  {response.sendRedirect("login.jsp");}
	  return;
}
if (w_opcao != null || w_opcao != ""){
	w_opcao = "";
	

	//Saldação ao usuario
	
	int w_Hora = Integer.parseInt((new java.text.SimpleDateFormat("HH")).format(new java.util.Date()));
	
	String w_AMPM = new java.text.SimpleDateFormat("a").format(new java.util.Date());
	
	if (w_Hora <= 0) {
	    situa_1 = "Boa Madrugada";
	    sol_1   = "imagens/noite.png";
	}
	if (w_Hora > 0 && w_Hora <= 6) {
	    situa_1 = "Boa Madrugada";
	    sol_1   = "imagens/noite.png";
	}
	if (w_Hora > 6 && w_Hora <= 12) {
	    situa_1 = "Bom Dia";
	    sol_1   = "imagens/dia.png";
	}
	if (w_Hora > 12 && w_Hora <= 18) {
	    situa_1 = "Boa Tarde";
	    sol_1   = "imagens/dia.png";
	}
	if (w_Hora >= 19 && w_Hora <= 23) {
	    situa_1 = "Boa Noite";
	    sol_1   = "imagens/noite.png";
	}
	
	
	String w_bomdia = situa_1 + " Seja Bem Vindo, " + w_nome3 + " hoje e, " + new java.text.SimpleDateFormat("EEEE dd 'de' MMMM 'de' yyyy").format(new java.util.Date()) + "<br />";
	
	String w_login        = request.getParameter("login");

	
	//Variaveis de Sessao
	
	String campo1a  = "";
	String campo2a  = "";
	String campo3a  = "";
	String campo4a  = "";
	String campo5a  = "";
	String campo6a  = "";

	// Prepara a Conexao com o Banco
	Class.forName(driver_pes);
	Connection Con = DriverManager.getConnection(connection_pes, user_pes, password_pes);
	Statement stm = Con.createStatement();

	// Busca Usuario
	sql1 = "SELECT * FROM tt_ser_01 WHERE login = '" + w_nome3 + "'";
	ResultSet res1 = stm.executeQuery(sql1);
	while(res1.next()){
		campo1a  = res1.getString("id");
		campo2a  = res1.getString("codigo");
		campo3a  = res1.getString("login");
		campo4a  = "SISTEMAXP,"+res1.getString("programas");
		campo5a  = res1.getString("tipo");
		campo6a  = res1.getString("semana");
	}
    // Fim Busca Usuario

	
	// Fim Verificar dia da Semana e Permissao da Tela 
    
	//out.println(campo1a + "<br>");
	//out.println(campo2a + "<br>");
	//out.println(campo3a + "<br>");
	//out.println(campo4a + "<br>");
	//out.println(campo5a + "<br>");
	//out.println(campo6a + "<br><br>");

	// Busca Permissao
	sql2 = "SELECT * FROM permissoes WHERE login = '" + campo3a + "' AND tabela = '" + w_tabela + "'";
	ResultSet res2 = stm.executeQuery(sql2);
	while(res2.next()){
		tabelap = res2.getString("tabela");
		per1    = res2.getString("incluir");
		per2    = res2.getString("alterar");
		per3    = res2.getString("excluir");
		per4    = res2.getString("imprimir");
	}
	// Fim Busca Permissao

	//out.println(tabelap + "<br>");
	//out.println(per1 + "<br>");
	//out.println(per2 + "<br>");
	//out.println(per3 + "<br>");
	//out.println(per4 + "<br>");

	

      out.write("\r\n");
      out.write("\r\n");


// obtém a quantidade de registros
PreparedStatement pstmt_x = Con.prepareStatement(
		"SELECT COUNT(*) AS c FROM useronline");
ResultSet rs_x = pstmt_x.executeQuery();
rs_x.next();
int total_user = Integer.parseInt(rs_x.getString("c"));


PreparedStatement pstmt2_x = Con.prepareStatement(
		   "SELECT usuario,timestamp,hora FROM useronline WHERE usuario = '" + w_nome3 + "'");
ResultSet res3_x = pstmt2_x.executeQuery();
while(res3_x.next()){
	
	usuarios2  = res3_x.getString("usuario");
	hora_user2 = res3_x.getString("hora");
}

if (usuarios2 != ""){
	
	
}else{
	
	
	try  
	{
		
		    int timedata = 0;
		    Calendar calendar = Calendar.getInstance();
		    long ms2          = calendar.getTimeInMillis();
		    int msc           = (int) (long) ms2;
		    
		    ///out.println("<br><br><br>" + ms2);

			int timestamp2    = msc;
			//out.println("<br><br><br>" + timestamp2);
			String remote_add = request.getRemoteAddr();
			String self       = request.getContextPath() + request.getServletPath();
			String data_time  = new java.text.SimpleDateFormat("dd/MM/yyyy").format(new java.util.Date());
			String data_hora  = new java.text.SimpleDateFormat("HH:mm:mm").format(new java.util.Date());
			String nome_user  = w_nome3;
			
			// Preparação para Inclusão  
			PreparedStatement stm1 = Con.prepareStatement("INSERT INTO useronline (timestamp,ip,arquivo,data,hora,usuario) VALUES (?,?,?,?,?,?)");   
			
			// Instancia Variavei para Salvar
			stm1.setInt(1, timestamp2);   
			stm1.setString(2, remote_add);   
			stm1.setString(3, self);   
			stm1.setString(4, data_time);   
			stm1.setString(5, data_hora);   
			stm1.setString(6, nome_user);   
				   
			stm1.executeUpdate();   
			
			stm1.close(); 
			
			}   
			catch(Exception ex)   
			{   
				  // Caso ocorra Erro 
				   out.println("<font color='red'>Erro ao Salvar !!!</font>");
			
			}  
	
	
}	




      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body onload=\"setTimeout('window.location.reload(true)',30000)\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<div style=\"Z-INDEX: 500; LEFT: 0px; WIDTH: 616px; POSITION: absolute; TOP: 0px; HEIGHT: 20px\">\r\n");
      out.write("<font color=\"#4682B4\" face=\"Ariel\" size=\"2\">&nbsp;&nbsp;");
 out.println(total_user); 
      out.write(" usuário(s) on-line</font>\r\n");
      out.write("</div>\r\n");
      out.write("<div style=\"Z-INDEX: 500; LEFT: 0px; WIDTH: 616px; POSITION: absolute; TOP: 17px; HEIGHT: 20px\">\r\n");
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src=\"imagens/kitt.gif\" />\r\n");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("<div align=\"center\">  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("\t\r\n");
      out.write("</html>\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
